### DISCUSSION TITLE
Aerospace not detecting Zathura PDF viewer (NULL-APP-BUNDLE-ID)

### DISCUSSION THREAD

**Discussion by SylvanFranklin** [nikitabobko/AeroSpace#1002] [potential-bugs]
I have the following in my config:
```toml
[[on-window-detected]]
if.app-id = 'NULL-APP-BUNDLE-ID'
if.app-name-regex-substring = 'zathura'
if.window-title-regex-substring = 'zathura'
run = 'move-node-to-workspace P'
```
Zathura does not move to space P. It does appear in the dock, application switcher, and is hidden when I run `aerospace list-apps macos-native-hidden`
