### DISCUSSION TITLE
Combine `on-window-detected` rules

### DISCUSSION THREAD

**Discussion by ivuorinen** [nikitabobko/AeroSpace#1029] [feature-ideas]
Hi there and thanks for the awesome app!

I currently have 17 different `if.app-id` rules in my config with the exactly the same `run` command, it's getting kinda messy. After searching the discussions I couldn't find anything that would help with this problem (only thing closest was the discussion about embedded script language).

Would it be possible to have something like `if.app-id-in` rule that would take an array (or is it table in toml parlance?) of app-id's and run the same command to the matched app. I imagine (without looking at the code, so excuse me if I'm getting this wrong) the internals would be looping the `if.app-id-in` array and basically doing the same matcher registration as `if.app-id` does.

For example from this:
```toml
[[on-window-detected]]
if.app-id = 'com.apple.finder' # Finder
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.Preview' # Preview
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.mail' # Mail
run = ['layout floating']
```

to this:
```toml
[[on-window-detected]]
if.app-id-in = ['com.apple.finder', 'com.apple.Preview', 'com.apple.mail']
run = ['layout floating']
```

That would help remove extra configuration lines and improve maintainability.

Thanks for considering this!
