### DISCUSSION TITLE
AeroSpace Not Working After Reinstallation

### DISCUSSION THREAD

**Discussion by andresalvareez** [nikitabobko/AeroSpace#1061] [potential-bugs]
##  What hapened
I created a Python virtual environment, and suddenly, AeroSpace stopped working. I tried restarting my computer and reopening it, but it still doesn’t work.  

I then uninstalled AeroSpace and deleted all related files I could find, but the issue persists. I'm not sure if anyone else has encountered this or if it's a new problem.  

- **Device:** MacBook Pro M2 Max (16")  
- **Operating System:** macOS  15.2 (24C101)

When running the following command in the terminal:  
```sh
/Applications/AeroSpace.app/Contents/MacOS/AeroSpace
```
I get the followin error:
```sh
Assertion failed: (is_bare_key_character(*cp) || is_string_delimiter(*cp)), function parse_key, file toml.hpp, line 14038.
[1]    64015 abort      /Applications/AeroSpace.app/Contents/MacOS/AeroSpace
```

My aerospace.toml config:
```toml
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

after-startup-command = [
    'exec-and-forget borders'
]

[gaps]
inner.vertical = 6
inner.horizontal = 6
outer.top = 6
outer.bottom = 2
outer.left = 1
outer.right = 1

[mode.main.binding]
alt-cmd-ctrl-enter = 'exec-and-forget nohup Alacritty'

alt-cmd-ctrl-h = 'focus left'
alt-cmd-ctrl-j = 'focus down'
alt-cmd-ctrl-k = 'focus up'
alt-cmd-ctrl-l = 'focus right'

alt-cmd-ctrl-shift-h = 'move left'
alt-cmd-ctrl-shift-j = 'move down'
alt-cmd-ctrl-shift-k = 'move up'
alt-cmd-ctrl-shift-l = 'move right'

alt-cmd-ctrl-tab = 'workspace-back-and-forth'
# alt-cmd-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next' # Moves all items in current monitor to other monitor

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
# alt-cmd-ctrl-h = 'split horizontal'
alt-cmd-ctrl-v = 'split vertical'

alt-cmd-ctrl-f = 'fullscreen'

alt-cmd-ctrl-s = 'layout v_accordion'               # 'layout stacking' in i3
alt-cmd-ctrl-w = 'layout h_accordion'               # 'layout tabbed' in i3
alt-cmd-ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-cmd-ctrl-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-cmd-ctrl-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-cmd-ctrl-a = 'focus parent'

alt-cmd-ctrl-1 = 'workspace 1'
alt-cmd-ctrl-2 = 'workspace 2'
alt-cmd-ctrl-3 = 'workspace 3'
alt-cmd-ctrl-4 = 'workspace 4'
alt-cmd-ctrl-5 = 'workspace 5'
alt-cmd-ctrl-6 = 'workspace 6'
alt-cmd-ctrl-7 = 'workspace 7'
alt-cmd-ctrl-8 = 'workspace 8'
alt-cmd-ctrl-9 = 'workspace 9'

alt-cmd-ctrl-shift-1 = 'move-node-to-workspace 1'
alt-cmd-ctrl-shift-2 = 'move-node-to-workspace 2'
alt-cmd-ctrl-shift-3 = 'move-node-to-workspace 3'
alt-cmd-ctrl-shift-4 = 'move-node-to-workspace 4'
alt-cmd-ctrl-shift-5 = 'move-node-to-workspace 5'
alt-cmd-ctrl-shift-6 = 'move-node-to-workspace 6'
alt-cmd-ctrl-shift-7 = 'move-node-to-workspace 7'
alt-cmd-ctrl-shift-8 = 'move-node-to-workspace 8'
alt-cmd-ctrl-shift-9 = 'move-node-to-workspace 9'

alt-cmd-ctrl-shift-c = 'reload-config'
alt-cmd-ctrl-r = 'mode resize'
alt-cmd-ctrl-t = 'mode service'

alt-cmd-ctrl-c = ['layout floating', 'resize width +200', 'resize height +200']

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
shift-backspace = ['close-all-windows-but-current', 'mode main']

alt-cmd-ctrl-h = ['join-with left', 'mode main']
alt-cmd-ctrl-j = ['join-with down', 'mode main']
alt-cmd-ctrl-k = ['join-with up', 'mode main']
alt-cmd-ctrl-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.pple.ical'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.apple.findmy'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Maps'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.valvesoftware.steam'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.facetime'
run = 'layout floating'

[[[on-window-detected]]
if.app-id = 'com.apple.findmy'
run = 'layout floating'

[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'layout floating'
```
