### DISCUSSION TITLE
Use PgUp and PgDn in key bindings

### DISCUSSION THREAD

**Discussion by spikespaz** [nikitabobko/AeroSpace#1129] [questions-and-answers]
I am trying to guess the name for the "Page Up" and "Page Down" keys, because the guide doesn't specify in any of the sections. I would expect these keys to be listed in "special keys".

It's a little funny that the discoverability of the key notations is only mentioned in a comment in the default config, so far as I have seen. Is there a comprehensive list of all these key notations so that I don't have to guess?

I have also tried:
```toml
[key-mapping.key-notation-to-key-code]
page_up = '0x74'
```
