### DISCUSSION TITLE
iTerm 2 quick terminal

### DISCUSSION THREAD

**Discussion by janglad** [nikitabobko/AeroSpace#1139] [questions-and-answers]
Hey, I was wondering what the best way to set up iTerm's quick terminal (through their global hotkey). I currently have this in my config, which kinda makes it work

```toml
[[on-window-detected]]
    if.app-id = 'com.googlecode.iterm2'
    if.window-title-regex-substring = "quake"
    run = 'layout floating'
```

but if I don't have my "real" iTerm windows hidden, they get focussed/unfocussed very briefly when closing the quick terminal. This results in a visual flash if they're on the same monitor as the current active workspace, or the cursor moving between the monitors if not. I know this could be something with iTerm itself but was wondering if someone had a good setup for this in combination with Aerospace.
