### DISCUSSION TITLE
aerospace windows layout become chaos when mac wake up from sleep almost every time

### DISCUSSION THREAD

**Discussion by xbunax** [nikitabobko/AeroSpace#1182] [potential-bugs] [answered]
I love this program but recently when I wake up mac from sleep the layout is always in chaos. I'm confused and I don't want to give each app a specified workspace I want to manage by myself. I even try to use hammserspoon to record layout when the mac is sleeping but useless. So I have no idea to solve this problem. :)

this is my version , system info and config
```
aerospace CLI client version: 0.17.1-Beta 407bad9fb54e9187912ba6cdd6b55df7a4c5d83e
AeroSpace.app server version: Unknown. The server is not running
```
```
                                              OS: macOS Sequoia 15.3.1 arm64
                                         │ ├ Kernel: Darwin 24.3.0
                                         │ ├󰏖 Packages: 284 (brew), 39 (brew-cask)
                                         │ ├ Shell: zsh 5.9
                                         │ ├ OS Age: 20153 days
                                         └ └ Uptime: 1 day, 8 hours, 23 mins
```

```toml
after-login-command = [
 # 'exec-and-forget ~/.config/aerospace/scripts/pin_window.sh $AEROSPACE_PREV_WORKSPACE $AEROSPACE_FOCUSED_WORKSPACE',
]

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  '$(brew --prefix)/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
  # '~/.config/aerospace/scripts/pin_window.sh $AEROSPACE_PREV_WORKSPACE $AEROSPACE_FOCUSED_WORKSPACE',
]
after-startup-command = [
  # 'exec-and-forget ~/.config/aerospace/scripts/bsp_tiling.sh',
]

on-focus-changed = [
  'exec-and-forget sketchybar --trigger aerospace_focus_change',
  'move-mouse window-lazy-center',
]

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

start-at-login = false

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 5
outer.right = 5
outer.bottom = [{ monitor.'^built-in retina display$' = 3 }, 5]
outer.top = [{ monitor.'^built-in retina display$' = 5 }, 40]

[exec] # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true # If you don't touch "exec" section,
[exec.env-vars] # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'
XDG_CONFIG_HOME = '${HOME}/.config'

[mode.main.binding]

alt-t=[
  'exec-and-forget ~/.config/aerospace/scripts/center_window.sh',
  'move-mouse window-force-center',
]

shift-alt-f = [
  'layout floating tiling',
  'mode main',
] 


# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
alt-k = ['exec-and-forget open /Applications/Kitty.app']
alt-z = ['exec-and-forget open -a Zotero']
alt-i = ['exec-and-forget open -a iTerm']
alt-g = ['exec-and-forget open -a Ghostty']
alt-w = ['exec-and-forget open /Applications/WeChat.app']
alt-q = ['exec-and-forget open /Applications/QQ.app']
alt-a = ['exec-and-forget open /Applications/Arc.app']
alt-f = ['exec-and-forget open -a Finder']
alt-s = ['exec-and-forget open -a Spotify']
alt-c = ['exec-and-forget open -a Visual\ Studio\ Code']

cmd-shift-backspace = [
  'exec-and-forget $(brew --prefix)/bin/sketchybar --trigger request_bg REQUEST_BG=false',
]
cmd-shift-w = [
  'exec-and-forget $(brew --prefix)/bin/sketchybar --trigger request_bg REQUEST_BG=true',
]

cmd-shift-down = [
  'exec-and-forget $(brew --prefix)/bin/sketchybar --trigger cycle_bg CYCLE=next',
]

cmd-shift-up = [
  'exec-and-forget $(brew --prefix)/bin/sketchybar --trigger cycle_bg CYCLE=prev',
]

cmd-shift-right = [
  'exec-and-forget $(brew --prefix)/bin/sketchybar --trigger select_bg SELECT=true',
]


cmd-shift-left = [
  'exec-and-forget $(brew --prefix)/bin/sketchybar --trigger select_bg SELECT=false',
]

cmd-shift-enter = [
  'exec-and-forget $(brew --prefix)/bin/sketchybar --trigger select_bg SELECT=true',
]

shift-ctrl-s=[
    'exec-and-forget $(brew --prefix)/bin/aerospace list-windows --all --format "%{window-id}%{workspace}%{app-bundle-id}" --json > ~/.config/aerospace/scripts/layout.json && osascript -e "display notification \"layout save\" with title \"success\""'
]

shift-ctrl-r=[
    'exec-and-forget ~/.config/aerospace/scripts/recovery_layout.sh'
]

shift-ctrl-c=[
    'exec-and-forget ~/.config/aerospace/scripts/custom_bar_themes light || ~/.config/aerospace/scripts/custom_bar_themes dark'
]

shift-ctrl-b=[
    'exec-and-forget ~/.config/aerospace/scripts/custom_bar_themes blur || ~/.config/aerospace/scripts/custom_bar_themes black'
]
shift-ctrl-t=[
    'exec-and-forget ~/.config/aerospace/scripts/change_theme.sh'
]

shift-ctrl-w=[
    'exec-and-forget ~/.config/aerospace/scripts/random_wallpapers.sh ~/.config/wallpapers'
]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-shift-enter = 'flatten-workspace-tree'
ctrl-w = 'close'

alt-shift-p = 'fullscreen'

# focus
shift-alt-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
shift-alt-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
shift-alt-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
shift-alt-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'
shift-alt-c='focus right --boundaries-action wrap-around-the-workspace'
# alt-shift-h = ['focus left']
# alt-shift-j = ['focus down']
# alt-shift-k = ['focus up']
# alt-shift-l = ['focus right']

# See  https://nikitabobko.github.io/AeroSpace/commands#move
cmd-shift-h = ['move left']
cmd-shift-j = ['move down']
cmd-shift-k = ['move up']
cmd-shift-l = ['move right']



# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-shift-h = 'resize smart -50'
ctrl-shift-l = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-cmd-1 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 1']
ctrl-cmd-2 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 2']
ctrl-cmd-3 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 3']
ctrl-cmd-4 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 4']
ctrl-cmd-5 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 5']
ctrl-cmd-6 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 6']
ctrl-cmd-7 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 7']
ctrl-cmd-8 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 8']
ctrl-cmd-9 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 9']
ctrl-cmd-0 = ['exec-and-forget ~/.config/aerospace/scripts/switch_workspaces.sh 10']


alt-cmd-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-cmd-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-cmd-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-cmd-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-cmd-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-cmd-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-cmd-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-cmd-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-cmd-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-cmd-0 = ['move-node-to-workspace 10', 'workspace 10']

alt-left = ['workspace prev --wrap-around']
alt-right = ['workspace next --wrap-around']
alt-cmd-c = ['move-workspace-to-monitor --wrap-around next']

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'focus-monitor --wrap-around next'

cmd-shift-s = 'mode service'
cmd-shift-d = 'mode RDP'

[workspace-to-monitor-force-assignment]
1 = 'main' # Monitor sequence number from left to right. 1-based indexing
2 = 'main' # Main monitor
3 = 'main' # Main monitor
4 = 'main' # Main monitor
5 = 'main' # Main monitor
6 = 'main' # Main monitor
# 7 = 'main'                # Main monitor
# 8 = 'main'                # Main monitor
# 9 = ['secondary', 'main'] # Main monitor
10 = ['secondary','main']          # Non-main monitor in case when there are only two monitors

[mode.floating.binding]
alt-t = [
    'exec-and-forget ~/.config/aerospace/scripts/center_window.sh',
    'move-mouse window-force-center',
    'mode main'
]
alt-shift-semicolon = 'mode service'
esc = 'mode main'

h = 'exec-and-forget ~/.config/aerospace/scripts/move-floating.sh -32 0'
j = 'exec-and-forget ~/.config/aerospace/scripts/move-floating.sh 0 32'
k = 'exec-and-forget ~/.config/aerospace/scripts/move-floating.sh 0 -32'
l = 'exec-and-forget ~/.config/aerospace/scripts/move-floating.sh 32 0'

shift-h = 'exec-and-forget ~/.config/aerospace/scripts/resize-floating-centered.sh -128 0'
shift-j = 'exec-and-forget ~/.config/aerospace/scripts/resize-floating-centered.sh 0 -128'
shift-k = 'exec-and-forget ~/.config/aerospace/scripts/resize-floating-centered.sh 0 128'
shift-l = 'exec-and-forget ~/.config/aerospace/scripts/resize-floating-centered.sh 128 0'

[mode.service.binding]
esc = ['reload-config', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

cmd-shift-h = ['join-with left', 'mode main']
cmd-shift-j = ['join-with down', 'mode main']
cmd-shift-k = ['join-with up', 'mode main']
cmd-shift-l = ['join-with right', 'mode main']

[mode.RDP.binding]
shift-cmd-q = ['reload-config', 'mode main']




[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
if.window-title-regex-substring = '^(?!WeChat \(Chats\)|微信 \(聊天\)).*$'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.tencent.qq'
if.window-title-regex-substring = '^(?!QQ).*$'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.blenderfoundation.blender '
if.window-title-regex-substring = '^(?!Blender).*$'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.360.cloudui'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Maps'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Photos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.weather'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'io.github.clash-verge-rev.clash-verge-rev'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.colliderli.iina'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.codeweavers.CrossOver'
run = ['layout floating']

[[on-window-detected]]
if.window-title-regex-substring = '(Picture in Picture|Picture-in-Picture|画中画)'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.bandisoft.mac.bandizip'
run = 'layout floating'

[[on-window-detected]]
if.app-id = "com.electron.1zilc.fishing-funds"
run = 'layout floating'

[[on-window-detected]]
if.app-id = "com.mathworks.matlab"
if.window-title-regex-substring = "^(?!MATLAB).*$"
run = 'layout floating'

[[on-window-detected]]
if.app-id = "com.xingin.discover"
run = 'layout floating'

[[on-window-detected]]
if.app-id = "com.hypergryph.arknights"
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = '(MuMu|exe)'
run = ['layout floating', 'move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
if.during-aerospace-startup = true
run = 'move-node-to-workspace 1'

# [[on-window-detected]]
# if.app-id = 'com.microsoft.autoupdate2'
# if.window-title-regex-substring='Microsoft AutoUpdate'
# run = 'close'

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.tencent.qq'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
if.during-aerospace-startup = true
run = 'move-node-to-workspace 4'

# [[on-window-detected]]
# if.window-title-regex-substring = '(不背|Zotero|Margin)'
# run = ['move-node-to-workspace 3']

```
