### DISCUSSION TITLE
Can't move focus through floating windows

### DISCUSSION THREAD

**Discussion by davibe** [nikitabobko/AeroSpace#1188] [potential-bugs] [answered]
The documentation clearly states moving focus should through floating windows should be possible. In my case it's not.

Example configuration to reproduce
```
default-root-container-layout = 'accordion'
default-root-container-orientation = 'horizontal'

[[on-window-detected]]
    check-further-callbacks = true
    run = ['layout floating'] 
```

The intention is to make all windows float "normally" but still leverage the aerospace functionalities for 'custom spaces' and 'focus'. Is that possible ?

**Comment by monsterhxw** [comment]
My Solution

**`$HOME/.config/aerospace/aerospace.toml`**
```toml
[mode.main.binding]
    alt-h = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace left || $HOME/.config/aerospace/scripts/focus-window.sh left'
    alt-j = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace down || $HOME/.config/aerospace/scripts/focus-window.sh down'
    alt-k = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace up || $HOME/.config/aerospace/scripts/focus-window.sh up'
    alt-l = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace right || $HOME/.config/aerospace/scripts/focus-window.sh right'
```

**`$HOME/.config/aerospace/scripts/focus-window.sh`**
```bash
#!/usr/bin/env bash

# AEROSPACE="/usr/local/bin/aerospace" # Intel Chip Homebrew Path
AEROSPACE="/opt/homebrew/bin/aerospace" # Apple Silicon Chip Homebrew Path

focus_window() {
  local direction=$1
  local window_ids=($($AEROSPACE list-windows --workspace focused --format '%{window-id}'))
  local window_count=${#window_ids[@]}

  if [[ $window_count -le 1 ]]; then
    exit 1
  fi

  local current_id=$($AEROSPACE list-windows --focused --format '%{window-id}')

  local current_index
  for i in "${!window_ids[@]}"; do
    if [[ "${window_ids[$i]}" == "$current_id" ]]; then
      current_index=$i
      break
    fi
  done

  local target_index
  case $direction in
    left|up)
      ((target_index = (current_index - 1 + window_count) % window_count))
      ;;
    right|down)
      ((target_index = (current_index + 1) % window_count))
      ;;
    *)
      exit 1
      ;;
  esac

  $AEROSPACE focus --window-id "${window_ids[$target_index]}"
}

if [[ $# -eq 1 ]]; then
  focus_window "$1"
else
  exit 1
fi
```
