### DISCUSSION TITLE
Alt key bindings stop working randomly

### DISCUSSION THREAD

**Discussion by audishos** [nikitabobko/AeroSpace#1205] [questions-and-answers] [answered]
Recently I've been encountering this problem where my alt-{key} bindings stop working. When I first boot, everything works as expected. Eventually, these bindings will just stop working and instead produce alt character text output such as:

alt-1: ¡
alt-2: ™
alt-3: £
etc.

I've tried messing with my keyboard settings and text input sources, but this hasn't helped. It also doesn't explain why these bindings work perfectly fine for an arbitrary amount of time and then just stop working. AeroSpace has been excellent up until now and I really want to resolve this!

**Comment by audishos** [comment]
Adding my config in-case it helps

```toml
# Reference: https://github.com/i3/i3/blob/next/etc/config

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffa6da95 inactive_color=0x00000000 width=8.0'
]

# Start AeroSpace at login
start-at-login = true

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 4
inner.vertical =   4
outer.left =       4
outer.bottom =     4
outer.top =        4
outer.right =      4

[mode.main.binding]
# Opens terminal with alt + enter - similar to sway
alt-enter = 'exec-and-forget open -n /Applications/kitty.app'

# i3 wraps focus by default
alt-h =         'focus --boundaries-action wrap-around-the-workspace left'
alt-j =         'focus --boundaries-action wrap-around-the-workspace down'
alt-k =         'focus --boundaries-action wrap-around-the-workspace up'
alt-l =         'focus --boundaries-action wrap-around-the-workspace right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-i = 'join-with up'
alt-u = 'join-with left'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace home'
alt-2 = 'workspace work'
alt-3 = 'workspace term'
alt-4 = 'workspace test'
alt-5 = 'workspace dsgn'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace home'
alt-shift-2 = 'move-node-to-workspace work'
alt-shift-3 = 'move-node-to-workspace term'
alt-shift-4 = 'move-node-to-workspace test'
alt-shift-5 = 'move-node-to-workspace dsgn'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# Floating window apps
[[on-window-detected]]
if.app-id = 'org.keepassxc.keepassxc'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.wulkano.kap'
run = 'layout floating'

# Assign apps to workspaces
[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace home'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace home'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace work'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace work'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace term'

[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
run = 'move-node-to-workspace test'
```

This config was working for some time without any changes before this issue started occurring.
