### DISCUSSION TITLE
Saving window positions?

### DISCUSSION THREAD

**Discussion by d1rewolf** [nikitabobko/AeroSpace#1221] [feature-ideas]
First of all, thanks so much for Aerospace. I've missed a tiling window manager so much, and it's nice to a have a great option for macOS.

I occasionally have AeroSpace crash or close for some other reason, and I lose all the time I've spent configuring my windows perfectly....they all revert to workspace 1 when I relaunch it.

Have you considered incorporating a way to save window positions and restore them in case of a crash?

Thanks in advance!

**Comment by codyw912** [comment]
There is a way to do this, sort of. You have to manually define the windows and the workspaces in your config via the `on-window-detected` callback, so it won't remember anything that's not in there, but it's a decent stopgap. I'm not sure it always keeps the layout of the workspace, so sometimes you have to change it around which is a bit annoying. Check this out: https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback

Here's an example from my config:
```
[[on-window-detected]]
	if.app-id = 'com.mitchellh.ghostty'
	run = 'move-node-to-workspace 1'

[[on-window-detected]]
	if.app-id = 'app.zen-browser.zen'
	run = 'move-node-to-workspace 1'
```

This is the only way I've found to get this done as of now.

**Reply by foice** [reply]
Is still (after 2+ years) the best way to restore windows position after quitting AeroSpace? Honestly this is a deal breaker for me.

**Reply by rwjack** [reply]
I watched a single video about aerospace, then I thought I could magically convert my amethyst config to aerospace, and have all these cool new features. The main thing that got me was the config simplicity and no need for native mac spaces.

Boy how wrong I was. Also love how popular LLMs hallucinated like crazy when I asked them if I could do x y z with aerospace. It actually turns out this project is severely lacking in basic TWM functionality.

Coming from qtile > pop os tiling > amethyst > (head against brick wall) aerospace

**Reply by markbabin** [reply]
Does amethyst have a window position save feature?

**Reply by rwjack** [reply]
@markbabin don't think so, although I just use the Mac built in "Assign to" feature, and every time i restart, everything is where it's supposed to be.

As for the too slow switching between workspaces, that's only when going left or right. If directly switching to a workspace (using integrated mac shortcuts) - the transition is fast enough.

**Comment by philsnow** [comment]
A big + gross hammer, but would something like this work?

```toml
after-startup-command = ['exec-and-forget source ~/.config/aerospace/restore-windows.sh']

[[on-window-detected]]
    if.during-aerospace-startup = false
    check-further-callbacks = true
    run = "exec-and-forget aerospace list-windows --all --format 'aerospace move-node-to-workspace --window-id %{window-id} %{workspace}' > ~/.config/aerospace/restore-windows.sh"
```
