### DISCUSSION TITLE
Create (and move to) a new workspace with an arbitrary ID?

### DISCUSSION THREAD

**Discussion by BatmanAoD** [nikitabobko/AeroSpace#1250] [questions-and-answers]
Is there any way to create a new workspace with an arbitrary ID/name? I'd like to add a binding to move the current node to a new workspace, but after reading the command list I'm not sure how to do that, other than by creating a separate binding for each possible workspace ID. Am I missing something obvious?

**Comment by nikitabobko** [comment]
It's not easily possible, but I saw people doing this (works only for numeric workspaces):

```toml
[mode.main.binding]
  alt-right = 'exec-and-forget aerospace move-node-to-workspace --focus-follows-window $(expr $(aerospace list-workspaces --focused) + 1)'
```

Probably something like `(next-numeric|prev-numeric)` could be supported if it's a popular enough request:
```toml
[mode.main.binding]
  alt-right = 'move-node-to-workspace --focus-follows-window next-numeric'
```

But it needs to be more thoroughly thought of and a more formalized proposal is welcome to `#feature-ideas`. For example, what should it do when the focused workspace is not a number?
