### DISCUSSION TITLE
Creating workspaces with arbitrary IDs

### DISCUSSION THREAD

**Discussion by BatmanAoD** [nikitabobko/AeroSpace#1267] [feature-ideas]
Original discussion: https://github.com/nikitabobko/AeroSpace/discussions/1250

I would like a way to create a workspace with an arbitrary ID, rather than hardcoding the possible workspace IDs in my configuration. This would also require some way to navigate to the newly-created workspaces.

Here's what I have in my configuration now:

```toml
[mode.main.binding]
    alt-shift-enter = 'exec-and-forget aerospace move-node-to-workspace --focus-follows-window $(expr $(aerospace list-workspaces --all | wc -l) + 1)'

    alt-comma = 'exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace prev --wrap-around'
    alt-period = 'exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace next --wrap-around'
    alt-shift-comma = 'move-node-to-workspace prev --wrap-around --focus-follows-window'
    alt-shift-period = 'move-node-to-workspace next --wrap-around --focus-follows-window'
```

This enables creating a new workspace with an ID based on the number of existing workspaces plus one, and then navigating through all workspaces without knowing what their IDs are.

It would be nice if these were built-in commands rather than complex `exec-and-forget`s.
