### DISCUSSION TITLE
Default all windows to be floating unless explicitly configured to be tiled

### DISCUSSION THREAD

**Discussion by majjoha** [nikitabobko/AeroSpace#1274] [questions-and-answers] [answered]
Thank you for the great work on Aerospace!

I am currently considering switching from Amethyst to Aerospace, but there is one key feature that is holding me back. I am unsure whether Aerospace already supports this and I've just missed it in the documentation, or if it is currently unsupported.

In Amethyst, I can configure it to float all applications by default unless they are explicitly listed to be tiled which can be done using the following setting in `amethyst.yml`:

```yaml
floating-is-blacklist: false
floating:
  - "com.apple.Maps"
  - "com.apple.Music"
  - "com.apple.Notes"
  - "com.apple.Photos"
  ...
```

This allows for a workflow where everything floats by default, and I opt in only the apps I want to tile.

In Aerospace, I understand that I can configure certain apps to float using:

```toml
[[on-window-detected]]
if.app-id = "com.apple.Maps"
run = ["layout floating"]
```

Is it possible to mimic Amethyst’s `floating-is-blacklist: false` behavior in Aerospace and make everything float by default? If not, would this be a feature you'd consider adding?

**Comment by nikitabobko** [comment, marked as answer]
Yes, it's possible:

```toml
[[on-window-detected]]
    check-further-callbacks = true
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = "com.apple.Maps"
    run = 'layout tiling'
```
