### DISCUSSION TITLE
iTerm2 keeps getting assigned to other monitors / workspace in another monitor

### DISCUSSION THREAD

**Discussion by nikitabobko** [nikitabobko/AeroSpace#1282] [potential-bugs]
Potential 0.18.0 regression

I just tried the artifacts published by lazywei. It seems my iTerm2 (hotkey floating window) keeps getting assigned to other monitors / workspace in another monitor. After setting it back to the current release version, this issue seems gone.

```toml
[[on-window-detected]]
  if.app-id = 'com.googlecode.iterm2'
  run = 'layout floating'
```

Originally reported by @zhenpewu https://github.com/nikitabobko/AeroSpace/issues/131#issuecomment-2797827726
