### DISCUSSION TITLE
AeroSpace option to enable only Workspaces feature and keep tiling disable

### DISCUSSION THREAD

**Discussion by PsN-1** [nikitabobko/AeroSpace#1303] [feature-ideas]
AeroSpace is a great app, but I've only be using its workspace features and somehow messing with the configurations I managed to disable the auto tiling features and use only the workspaces (the new macOS tilling features have been enough for my usage).

Maybe, maybe, It was possible to add an option to disable other features and only use the workspaces (maybe get some performance gains with it, maybe being able to enable Macs "Displays have separate Spaces" so we can use Mac native drag window to edge or holding `option` key features without the performance issues).

This is basically the only configuration I truly need from AeroSpace, and I know that for some people it's also the same.
```toml
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'

alt-ctrl-1 = 'move-node-to-workspace 1'
alt-ctrl-2 = 'move-node-to-workspace 2'
alt-ctrl-3 = 'move-node-to-workspace 3'
alt-ctrl-4 = 'move-node-to-workspace 4'
alt-ctrl-5 = 'move-node-to-workspace 5'
alt-ctrl-6 = 'move-node-to-workspace 6'
alt-ctrl-7 = 'move-node-to-workspace 7'
alt-ctrl-8 = 'move-node-to-workspace 8'
alt-ctrl-9 = 'move-node-to-workspace 9'
```

My full messy configs:
https://gist.github.com/PsN-1/ea83a84820df7e2bd5a7c54cba65d59c
