### DISCUSSION TITLE
v0.18.2: aerospace is capturing windows it shouldn't

### DISCUSSION THREAD

**Discussion by twio142** [nikitabobko/AeroSpace#1317] [potential-bugs] [answered]
Like the ones of notification center, or [Uebersicht](https://github.com/felixhageloh/uebersicht) (desktop widgets).

This behavior happens from time to time, causing the widgets (both the built-in ones and the Uebersicht ones) on other monitors to be dragged onto the main one.

When I close these windows with the cli, the widgets can be manually dragged back to the other monitor again.

**Comment by nikitabobko** [comment, marked as answer]
Tracking issue: https://github.com/nikitabobko/AeroSpace/issues/1324

**Comment by nikitabobko** [comment]
> Like the ones of notification center

What do you mean?

**Reply by twio142** [reply]
Those are seemingly in charge of the built-in widgets. They have the bundle ID `com.apple.notificationcenterui`

**Comment by ChristinWhite** [comment]
I've run into three more modal/floating windows that are also being treated as normal windows as well. I've been able to work around them with window-title-regex-substring in each case so far, so this hasn't impacted my workflow much.

The three I've run into are 1Password's quick access modal, Godspeed's quick entry and Anybox's bookmark dialog which I frequently launch from my browser.

```toml
# Main window, always begins with the collection name.
[[on-window-detected]]
if.app-id = "com.1password.1password"
if.window-title-regex-substring = "^MyCollectionName"
run = "move-node-to-workspace O"

# Quick access modal, always uses `Quick Access` for title string.
[[on-window-detected]]
if.app-id = "com.1password.1password"
if.window-title-regex-substring = "^Quick Access"
run = "layout floating"

# Main window, title string shows the location followed by the app name, for example `Today | Godspeed`
[[on-window-detected]]
if.app-id = "com.godspeedapp.Godspeed-setapp"
if.window-title-regex-substring = ".+Godspeed"
run = "move-node-to-workspace P"

# Quick entry modal, title string is always `Godspeed`
[[on-window-detected]]
if.app-id = "com.godspeedapp.Godspeed-setapp"
if.window-title-regex-substring = "^Godspeed$"
run = "layout floating"

# Anybox main window, has a title string
[[on-window-detected]]
if.app-id = "cc.anybox.Anybox"
if.window-title-regex-substring = ".+"
run = "move-node-to-workspace W"

# Anybox bookmark modal, blank title string
[[on-window-detected]]
if.app-id = "cc.anybox.Anybox"
if.window-title-regex-substring = "^$"
run = "layout floating"
```

[debug-windows output](https://gist.github.com/ChristinWhite/1c6ec12d2b246efdfde1e4114fb9c761), as much as I was albe to collect anyway.

If I can provide any other helpful details or if you'd prefer reply to #1324 instead let me know.

**Reply by twio142** [reply]
I've also set hooks for windows with those app IDs to make them float. But sometimes after the screen was unlocked, some of these windows are still dragged onto another monitor.

Also, even when these windows are floating, they still belong to a certain workspace and therefore are not visible when switched to another workspace. This is apparently not ideal for desktop widgets. The wished behavior should be ignoring these windows completely.

BTW I'm having this issue with arc browser's picture-in-picture window as well.

**Reply by ChristinWhite** [reply]
The issue with them getting moved to the other workspace is why I also have specific rules for the main window and don't just use the app-id, the workspace rules only fire if it's actually the main window (exempting edge-cases I haven't seen and addressed *yet*). I haven't had any trouble getting these rules to work reliably since setting them up this way.

I do also have an additional rule for 1Password to manage the `Open Item In New Window` case. I didn't mention it because it's not related to the regression, but it is an example of needing to address each window separately if you use main-window rules. That said, you use Regex to handle multiple window types together if desired.

```toml
[[on-window-detected]]
if.app-id = "com.1password.1password"
if.window-title-regex-substring = "^(?!MyCollectionName|Quick Access)"
run = "layout floating"
```
