### DISCUSSION TITLE
I have spaces 11 and 12 despite only 10 (0 to 9) defined

### DISCUSSION THREAD

**Discussion by danielo515** [nikitabobko/AeroSpace#1329] [questions-and-answers]
I’ve configured AeroSpace to only ever use workspaces 1–9 (and then letters A, B). However, AeroSpace still creates spaces 11–12 automatically when I connect a second external monitor

Also, the workspace to monitor assignment is not working. Workspaces 11 and 12 are assigned to builtin and the second monitor respectively.

This is my `~/.aerospace.toml`:
   
```toml
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xff00e3e4 inactive_color=0xff494d64 width=5.0',
    # Notify that AeroSpace has started
    'exec-and-forget curl -s -G -d "message=Aerospace%20started"  "http://localhost:8765/service-mode" > /dev/null',
]


on-focus-changed = [
    "exec-and-forget osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'",
]

exec-on-workspace-change = [
    '/bin/zsh',
    '-c',
    '/usr/bin/osascript -e "tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\""',
]


# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 40

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical = 15
outer.top = 35
outer.bottom = 0
outer.left = 10
outer.right = 10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# Disable "hide application" and "hide others" commands
cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-ctrl-shift-j = 'move left'
alt-ctrl-shift-k = 'move right'
alt-ctrl-shift-up = 'move up'
alt-ctrl-shift-down = 'move down'
alt-ctrl-right = 'join-with right'
alt-ctrl-left = 'join-with left'
alt-ctrl-up = 'join-with up'
alt-ctrl-down = 'join-with down'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-ctrl-shift-left = 'resize smart -50'
alt-ctrl-shift-right = 'resize smart +50'
alt-ctrl-shift-f = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
alt-a = 'workspace a'
alt-b = 'workspace b'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# in my globe 80 holding M keys gives you alt+control
alt-ctrl-1 = 'move-node-to-workspace 1'
alt-ctrl-2 = 'move-node-to-workspace 2'
alt-ctrl-3 = 'move-node-to-workspace 3'
alt-ctrl-4 = 'move-node-to-workspace 4'
alt-ctrl-5 = 'move-node-to-workspace 5'
alt-ctrl-6 = 'move-node-to-workspace 6'
alt-ctrl-7 = 'move-node-to-workspace 7'
alt-ctrl-8 = 'move-node-to-workspace 8'
alt-ctrl-9 = 'move-node-to-workspace 9'
alt-ctrl-0 = 'move-node-to-workspace 10'
alt-ctrl-a = 'move-node-to-workspace a'
alt-ctrl-b = 'move-node-to-workspace b'
alt-ctrl-shift-r = [
    'reload-config',
    'exec-and-forget curl -s -G -d "message=Config%20reloaded"  "http://localhost:8765/service-mode" > /dev/null',
]
ctrl-left = 'workspace --wrap-around prev'
ctrl-right = 'workspace --wrap-around next'
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-ctrl-shift-semicolon = [
    "mode service",
    'exec-and-forget curl -s "http://localhost:8765/service-mode" > /dev/null',
]
# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = [
    'reload-config',
    'mode main',
    'exec-and-forget curl -s -G -d "message=Config%20reloaded"  "http://localhost:8765/service-mode" > /dev/null',
]
r = ['flatten-workspace-tree', 'mode main'] # reset layout
# Toggle between floating and tiling layout
f = ['layout floating tiling']
backspace = ['close-all-windows-but-current', 'mode main']
h = ['join-with left']
l = ['join-with right']
j = ['join-with down']
k = ['join-with up']

### Window Rules
# Floating apps
[[on-window-detected]]
if.app-name-regex-substring = '(Finder|Hammerspoon|Huddle|Flameshot|Raycast)'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = '(Software Update|Update Available|Updating Ghostty|MetaMask)'
run = 'layout floating'

# Ghostty workaround
[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = ["layout floating"]


[[on-window-detected]]
if.app-name-regex-substring = "time tracker app"
run = ["move-node-to-workspace 1"]

[[on-window-detected]]
if.app-id = "OrcaSlicer"
run = ["layout floating", "move-node-to-workspace 7"]

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'main'
7 = ['secondary', 'main']
8 = ['secondary', 'main']
9 = ['builtin', 'secondary', 'main']
10 = ['builtin', 'secondary', 'main']
```
