### DISCUSSION TITLE
How can I define a workspace where misc/random windows will be placed?

### DISCUSSION THREAD

**Discussion by ijpatricio** [nikitabobko/AeroSpace#1391] [questions-and-answers]
Hey everyone,

Fantastic piece of software. Only at a third try it clicked for me, but now there's now way back, it seems! ❤️ 

At times, I quit Aerospace, when not performing coding tasks, work tasks.
When starting Aerospace, all apps land in "workspace 1", and I can't understand why!

For context, it might be relevant.

I have 4 monitors, and got all workspaces well defined, and well assigned to their monitor.

From left to right:
a,z => telecue, 14"
w,s,x => vertical left
1-7 + 0 => main -> can't use 8 and 9, bc in my PT layout, alt-8 and alt-9 are the square brackets `[ ]`
e,d,c => vertical right

What I expected would be that on start, all my defined "Apps per workspace" go there - because of `on-window-detected`

Therefore, I would assume. PHPStorm would be the only app going into `workspace 1`.
Why? Because `workspace 0` is before, on config and on the UI

![CleanShot 2025-05-07 at 13 21 06](https://github.com/user-attachments/assets/aa9d744b-38ac-498d-b96f-b2c08eedf7c1)

What's happening is that ALL APPS not mentioned in a `on-window-detected`, also end up in `workspace 1`

Any ideas? 

Thank you!

My config, so that the above makes sense:

```toml 



# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# Start AeroSpacee at login
start-at-login = false

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget borders active_color=0xffffafff inactive_color=0xff404344 width=10.0',
  'workspace w',
  'workspace e',
  'workspace 1',
]


# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       15
outer.bottom =     15
outer.top =        15
outer.right =      15


# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace

# On top for catch-all
alt-0 = 'workspace 0'

# Center
alt-1 = 'workspace 1' # phpstorm
alt-2 = 'workspace 2' # terminals
alt-3 = 'workspace 3' # browsers
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
#left
alt-w = 'workspace w'
alt-s = 'workspace s'
alt-x = 'workspace x'
#right
alt-e = 'workspace e'
alt-d = 'workspace d'
alt-c = 'workspace c'
# Telecue
alt-a = 'workspace a'
alt-z = 'workspace z'


# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-0 = 'move-node-to-workspace 0'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
#left
alt-shift-w = 'move-node-to-workspace w'
alt-shift-s = 'move-node-to-workspace s'
alt-shift-x = 'move-node-to-workspace x'
#right
alt-shift-e = 'move-node-to-workspace e'
alt-shift-d = 'move-node-to-workspace d'
alt-shift-c = 'move-node-to-workspace c'
# Telecue
alt-shift-a = 'move-node-to-workspace a'
alt-shift-z = 'move-node-to-workspace z'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'


# See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
# Center monitor (MAG321CURV)
'1' = 'MAG321CURV'
'2' = 'MAG321CURV'
'3' = 'MAG321CURV'
'4' = 'MAG321CURV'
'5' = 'MAG321CURV'
'6' = 'MAG321CURV'
'7' = 'MAG321CURV'

# Left monitor (LEN L28u-30 (1))
'w' = '^LEN\s+L28u-30\s*\(1\)$'
's' = '^LEN\s+L28u-30\s*\(1\)$'
'x' = '^LEN\s+L28u-30\s*\(1\)$'

# Right monitor (LEN L28u-30 (2))
'e' = '^LEN\s+L28u-30\s*\(2\)$'
'd' = '^LEN\s+L28u-30\s*\(2\)$'
'c' = '^LEN\s+L28u-30\s*\(2\)$'

# Top monitor (Wimaxit FHD)
'a' = 'Wimaxit FHD'
'z' = 'Wimaxit FHD'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']


[[on-window-detected]]
if.app-id = 'com.jetbrains.PhpStorm'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace w'

[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = 'move-node-to-workspace e'
[[on-window-detected]]
if.app-id = 'com.DanPristupov.Fork'
run = 'move-node-to-workspace e'
[[on-window-detected]]
if.app-id = 'be.spatie.ray'
run = 'move-node-to-workspace e'
[[on-window-detected]]
if.app-id = 'com.tinyapp.TablePlus-setapp'
run = 'move-node-to-workspace e'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace c'
[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = 'move-node-to-workspace c'
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace c'




```

**Comment by nikitabobko** [comment]
I don't understand your question. Please rephrase it in the form of template from #potential-bugs https://github.com/nikitabobko/AeroSpace/blob/main/.github/DISCUSSION_TEMPLATE/potential-bugs.yml

**Comment by ijpatricio** [comment]
Thank you @nikitabobko for this software!

Ok, let's forget previous context, and make a smaller one:

Steps to reproduce:
1.  Open apps: Chrome, Safari, and Calendar.
2. Chrome is configured for `workspace 1`. Others don't have any config.
3.  Start `aerospace`.

Expected result:
`workspace 0` would have Safari and Calendar.
`workspace 1` would have Chrome.

Actual result:
`workspace 1` has all the apps.

### Additional info

```shell
$ aerospace -v
aerospace CLI client version: 0.18.4-Beta 96c745197e2ee22e61c0bda17427166a1695b8a7
AeroSpace.app server version: 0.18.4-Beta 96c745197e2ee22e61c0bda17427166a1695b8a7
```

**Reply by nikitabobko** [reply]
I can't reproduce this problem. If I use `on-window-detected` to assign applications to particular workspaces like so:

```toml
[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    run = 'move-node-to-workspace 1'
```

then when I run AeroSpace all windows except for Chrome end up on the zero workspace (Given that I defined `workspace 0` in the config). Chrome windows get assigned to workspace 1 as expected
