### DISCUSSION TITLE
Shift focus to an empty workspace doesn't change windows focus

### DISCUSSION THREAD

**Discussion by cristianoliveira** [nikitabobko/AeroSpace#1411] [potential-bugs]
### Body

Hello there!
Thanks for this project, I really missed i3wm like WM for mac

I'm struggling with an issue regarding focus and empty spaces

## Problem
I noticed that once you move focus to an empty workspace, the window originally focused on the previous workspace remain focused, it only lose focus when you click on the empty desktop. This causes issues when using the command `exec-and-forget open /Application/MyApp.app` which assuming the "MyApp" was focused it won't retake focus, cuz the builtin WM think it is already focused. See steps to reproduce and the video

https://github.com/user-attachments/assets/d7142af9-7eae-4e8f-9d6c-4d0bb70d5534

## Issue

Assuming this config
```toml
[mode.main.binding]
cmd-0 = "workspace 0"
cmd-1 = "workspace 1" # the terminal is here
cmd-2 = "workspace 2" # this workspace is empty

ctrl-cmd-enter = ["exec-and-forget open -a ~/Applications/Alacritty.app"]
```

Steps to reproduce:
1. Focus on a window, for instance the terminal.
2. Move focus to a empty workspace (cmd+2)
3. Press cmd + ctrl + enter  

Expected result:
Assuming the ws 1 is focused on `MyApp`
Upon shifting focus to an empty space the window focus goes to finder(maybe?)
Once you call `open /Application/MyApp.app` the focus goes back to it

Actual result:
Focus stays with previous window and upon calling `open  /Application/MyApp.app`, since for the builtin WM "MyApp" is focused, it does nothing

### Additional info

```shell
$ aerospace -v

aerospace CLI client version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
AeroSpace.app server version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58

$sw_vers -productVersion                                                                                                                                   [13:44:44]
15.4.1

```
