### DISCUSSION TITLE
How to move window accross workspaces on multiple monitors?

### DISCUSSION THREAD

**Discussion by Diaoul** [nikitabobko/AeroSpace#1413] [questions-and-answers]
Basically what I want is the same behavior as `--boundaries all-monitors-outer-frame` for `focus` but for `move` such that I can move windows in the next monitor when hitting the boundary.

Is that possible? How can I workaround this?

```toml
# What currently works for focus
alt-h = 'focus --boundaries all-monitors-outer-frame left'
alt-j = 'focus --boundaries all-monitors-outer-frame down'
alt-k = 'focus --boundaries all-monitors-outer-frame up'
alt-l = 'focus --boundaries all-monitors-outer-frame right'

# What I'd love to work for moving as well
alt-shift-h = 'move --boundaries all-monitors-outer-frame left'
alt-shift-j = 'move --boundaries all-monitors-outer-frame down'
alt-shift-k = 'move --boundaries all-monitors-outer-frame up'
alt-shift-l = 'move --boundaries all-monitors-outer-frame right'
```

Oh and by the way, thanks for the awesome work 🎉  It never felt better to use a Mac thanks to AeroSpace 🙇
