### DISCUSSION TITLE
MS Teams window identification question

### DISCUSSION THREAD

**Discussion by burgessa23** [nikitabobko/AeroSpace#1418] [questions-and-answers]
Hi,

Does anyone know of a way to identify spawned windows in meeting apps like Teams and Zoom?
I'd like to be able to have the main teams window on workspace 2 (horizontal accordion) but have meeting windows float.

**Comment by burgessa23** [comment]
`aerospace list-windows --app-bundle-id com.microsoft.teams2 --monitor all` returns:

```
16316 | Microsoft Teams | Calendar | Microsoft Teams
16466 | Microsoft Teams | Leads Meeting | Microsoft Teams
```

The meeting window seems to reliably be the second item

**Comment by DarthImriel** [comment]
You could try a window detection callback using app-id and window-title regex for identification, and then have the callback run to set that as a floating layout.

Sample for Teams, assuming "Meeting" is in the title of the app when it's a meeting/call. This wouldn't work for every new spawned window, though you may be able to tweak it as such. 

[[on-window-detected]]
    if.app-id = 'com.microsoft.teams2'
    if.window-title-regex-substring = 'Meeting'
    run = ['layout floating']

**Reply by IOIO72** [reply]
I used a similar approach and needed to differentiate between Chats and Video Calls. To track changes in titles, I counted the number of `|`.

Here's the one for Calls:
```toml
[[on-window-detected]]
    if.app-id = 'com.microsoft.teams2'
    if.window-title-regex-substring = '^[^|]*\|[^|]*\|[^|]*\|[^|]*Microsoft Teams$'
    run = 'move-node-to-workspace 1'
```

Add one more `[^|]*\|` for Chats.

Unfortunately, I can't seem to manage Teams windows properly because Teams itself interferes with their arrangement.
