### DISCUSSION TITLE
Get workspaces which are empty for sketchybar?

### DISCUSSION THREAD

**Discussion by karamanliev** [nikitabobko/AeroSpace#1465] [general]
Currently I have this:
```bash
# ./sketchybar/items/spaces.sh
#!/usr/bin/env bash

sketchybar --add event aerospace_workspace_change

# Get all workspaces
WORKSPACES=$(aerospace list-workspaces --all)

# Get empty workspaces
EMPTY_WORKSPACES=$(aerospace list-workspaces --monitor all --empty)

for i in $WORKSPACES; do
	sid=$i

	if echo "$EMPTY_WORKSPACES" | grep -q "$sid"; then
		empty_sid=$sid
	fi

	sketchybar --add space space.$sid left \
		--subscribe space.$sid aerospace_workspace_change system_woke \
		--set space.$sid associated_space=$sid \
		label.drawing=off \
		icon.padding_left=9 \
		icon.padding_right=9 \
		background.padding_left=2 \
		background.padding_right=2 \
		background.color=0x22ffffff \
		background.corner_radius=4 \
		background.height=22 \
		background.drawing=off \
		script="$PLUGIN_DIR/space.sh $empty_sid"
done
```

```bash
# ./sketchybar/plugins/space.sh
#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

SPACE_CLICK_SCRIPT="aerospace workspace $SID"

EMPTY_SID=$1

if [ $SID = "$EMPTY_SID" ]; then
	INACTIVE_COLOR="$COMMENT"
else
	INACTIVE_COLOR="$WHITE"
fi

if [ $SID = "$FOCUSED_WORKSPACE" ]; then
	sketchybar --animate tanh 5 --set "$NAME" \
		icon.color="$INACTIVE_COLOR" \
		icon="$SID" \
		background.drawing=on \
		click_script="$SPACE_CLICK_SCRIPT"
else
	sketchybar --animate tanh 5 --set "$NAME" \
		icon.color="$INACTIVE_COLOR" \
		icon="$SID" \
		background.drawing=off \
		click_script="$SPACE_CLICK_SCRIPT"
fi
```

```toml
# aerospace.toml
...
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]
...
```

Which results to this:
<img width="192" alt="image" src="https://github.com/user-attachments/assets/2f889b04-5bab-4825-b49e-6a6d6065580c">

This is great and exactly what I am looking for, but I can't find a way to have this updated when a workspace actually becomes empty or not. I've searched for something relevant in the documentation of aerospace but was not able to find anything sufficient. Am I missing something, or this is just not possible currently?

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - --empty
  - list-workspaces 
  - "hide workspaces"
  - sketchybar
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - list-workspaces
  - events
  - on-change
  - sketchybar

**Comment by nikitabobko** [comment]
Please don't ignore the checklist in the issue template

UPD: converted the issue into a discussion

**Comment by karamanliev** [comment]
Updated my post with the checklist required.

**Comment by mkhattat** [comment]
I stumbled upon this issue since I was going to achieve something similar. In my case, I wanted to hide empty workspaces. So I just came up with this workaround. I put it here for anyone interested:

`sketchybarrc`
```bash
sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done
```

`aerospace.sh`
```bash
#!/usr/bin/env bash
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

SID="$1"
PADDING_LEFT=9
PADDING_RIGHT=10

INACTIVE_COLOR=$ACCENT_COLOR
EMPTY_WS_COLOR=$GRAY_ITEM_BG_COLOR
	
CURRENT_WORKSPACE=$(<~/.current_workspace)
EMPTY_WORKSPACES=$(<~/.empty_workspaces)

if [ "$SID" = "$CURRENT_WORKSPACE" ]; then
	sketchybar --set $NAME drawing=on background.drawing=on \
		icon.drawing=off \
		background.color=$ACCENT_COLOR \
		label.color=$BAR_COLOR \
		label="$1" \
		label.padding_right=$PADDING_RIGHT \
		label.padding_left=$PADDING_LEFT
else
		if [[ $EMPTY_WORKSPACES == *"$SID"* ]]; then
			# INACTIVE_COLOR=$EMPTY_WS_COLOR
			sketchybar --set $NAME drawing=off
			exit 0
		fi
		sketchybar --set $NAME drawing=on background.drawing=off \
			icon.drawing=off \
			label.color=$INACTIVE_COLOR \
			label="$1" \
			label.padding_right=$PADDING_RIGHT \
			label.padding_left=$PADDING_LEFT
fi
```
In your case comment out this line `# INACTIVE_COLOR=$EMPTY_WS_COLOR`  and remove 2 lines below it. Also make sure to change the color variables.

`aerospace.toml`
```toml
# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'echo $AEROSPACE_FOCUSED_WORKSPACE > ~/.current_workspace'
]
# Notify Sketchybar about moving windows to a different workspace and changing workspaces
on-focus-changed = ['exec-and-forget aerospace list-workspaces --monitor all --empty > ~/.empty_workspaces && sketchybar --trigger aerospace_workspace_change']
```

There are 2 things to consider:
* For performance reasons I use `~/.current_workspace` and `~/.empty_workspaces`. This is because if you have 9 workspaces, for example, then the event `aerospace_workspace_change` will be triggered 9 times and running the aerospace commands inside `aerospace.sh` directly will slow down the UI.
* This has one disadvantage: When I press mode+num to change the workspace, the sketchybar will be updated after the window is visible on the screen. There will be a slight delay. I like to see the sketchybar to be updated as soon as I press the key on my keyboard. So in that case you may change the `aerospace.toml` to the following:
```toml
# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'echo $AEROSPACE_FOCUSED_WORKSPACE > ~/.current_workspace && sketchybar --trigger aerospace_workspace_change'
]
# Notify Sketchybar about moving windows to a different workspace and changing workspaces
on-focus-changed = ['exec-and-forget sleep 0.1 && aerospace list-workspaces --monitor all --empty > ~/.empty_workspaces && sketchybar --trigger aerospace_workspace_change']
```
The sleep command is there to prevent race condition.

It would be cool to see an event that decouples changes to windows inside a workspace from workspace changes. Something like `workspace-window-change` that would capture ONLY changes to windows in a workspace like moving a node out of the workspace or creating and destroying windows in the workspace BUT NOT workspace switching. Then that would work better with sketchybar.
