### DISCUSSION TITLE
Feature-Idea: Command to Dynamically Float a Window and Persist the Setting

### DISCUSSION THREAD

**Discussion by junqi-lu** [nikitabobko/AeroSpace#1468] [feature-ideas] [answered]
Currently, if a user wants to make a specific application window always float, they need to:
1.  Identify a stable property of the window (e.g., `app-id`, `app-name`). Obtaining the `app-id` is not always straightforward for all users and might require using external tools or commands (e.g., `aerospace list-windows --focused` or similar).
2.  Manually edit the Aerospace configuration file.
3.  Add a new rule specifying the identifier and the desired floating state.
4.  Reload the Aerospace configuration.

This process can be cumbersome.

So can we have a new Aerospace command, like `float-and-persist-focused` (or a similar intuitive name).

**How it would work (example workflow):**
1.  The user focuses the window they want to make permanently floating.
2.  The user executes the command or trigger it with shortcut keys.
3.  Upon execution:
    *   The currently focused window is **immediately** set to floating mode.
    *   Aerospace automatically determines the most suitable and stable identifier for this window (preferably `app_id` if available and reliable, falling back to other properties if necessary).
    *   Aerospace **appends** a new rule to the user's configuration file (e.g., `~/.aerospace.toml`) that will make future instances of this application/window float by default. For example, it might add something like:
        ```toml
        # ~/.aerospace.toml
        # ... existing user config ...

        # Rule added by 'aerospace float-and-persist-focused' on YYYY-MM-DD HH:MM:SS
        [[on-window-detected]]
        if.app-id = "com.example.AppName" # Or whatever identifier Aerospace uses
        run = "layout floating" # Or equivalent action to make it float
        ```
    *   Aerospace could automatically reload its configuration.

**Comment by nikitabobko** [comment]
The idea sounds interesting, I see what use case you're trying to cover.

It came as a surprise to me that the following is valid TOML code:

```toml
[[on-window-detected]]
  foo = 1

[something-else]
  bar = 3

[[something-completely-else]]
  bar = 4

[[on-window-detected]]
  foo = 2
```

But even so, just appending `on-window-detected` not going to work if the user already has a callback that matches the window, because the callback that is declared earlier will take precedence over the callback that is declared later.
