### DISCUSSION TITLE
Aerospace support on macOS Tahoe (macOS 26)

### DISCUSSION THREAD

**Discussion by amantinband** [nikitabobko/AeroSpace#1471] [potential-bugs] [answered]
### Body

Hey guys! Don't see an existing issue so dropping this here - has anyone tested on macOS Tahoe?

Just updated to the latest developer beta and other than the windows resizing nothing else seems to work

**Comment by adusak** [comment]
Hello, I've been trying to use it for 2 days now, and for me, it mostly works (in terms of my workflow). The biggest issue I have observed so far is ghost windows detected by Aerospace. When I list windows in a workspace, it outputs windows from apps I killed. That is causing the actually visible windows to be resized.

**Reply by TheNetAdmin** [reply]
Same problem with phantom windows, they are closed for sure but AeroSpace still think they exist, and make the existing windows much smaller than it should

**Reply by fozyus** [reply]
same here, can't find any solution for this

**Reply by TheNetAdmin** [reply]
@nikitabobko Hi I think this is a common enough issue on macOS 26, shall we create an issue for this?

**Reply by SConaway** [reply]
An annoying workaround is to run `aerospace list-windows --all` and then `aerospace close --window-id <ID from before>` for each dead workspace.

**Reply by TheNetAdmin** [reply]
Nice workaround! I further developed such small python script, and bind it to `alt-g` keybinding by `alt-g = 'exec-and-forget python3 ~/bin/aerospace_cleanup.py cleanup'`


So whenever I observe a weird ghost window, I just `alt-g` and it's gone:

```python
import typer
from invoke import run
from typing import Dict

app = typer.Typer()

@app.command()
def cleanup():
    res = run("aerospace list-windows --all")

    def parse(w: str) -> Dict[str, str]:
        id, name, title = w.strip().split("|")
        return {
            "id": id.strip(),
            "name": name.strip(),
            "title": title.strip()
        }
    
    windows = [parse(w) for w in res.stdout.strip().split("\n")]
    windows = [w for w in windows if len(w["title"]) == 0]

    for w in windows:
        run(f"aerospace close --window-id {w['id']}")

```

**Reply by PaulvSchaik** [reply]
@TheNetAdmin I get the error: ModuleNotFoundError: No module named 'typer'

I now use 'close-all-windows-but-current' bound to alt-q a lot and it makes it workable, I don't have a whole lot of windows open.

**Reply by mblarsen** [reply]
@PaulvSchaik here is a version that doesn't require external libs.

```python
import subprocess
from typing import Dict


def cleanup():
    res = subprocess.run(
        ["aerospace", "list-windows", "--all"], capture_output=True, text=True
    )

    def parse(w: str) -> Dict[str, str]:
        id, name, title = w.strip().split("|")
        return {"id": id.strip(), "name": name.strip(), "title": title.strip()}

    windows = [parse(w) for w in res.stdout.strip().split("\n")]
    print(f"{windows=}")
    windows = [w for w in windows if len(w["title"]) == 0]

    for w in windows:
        subprocess.run(["aerospace", "close", "--window-id", w["id"]])


if __name__ == "__main__":
    cleanup()
```

**Reply by fozyus** [reply]
I have written this one

```
#!/bin/bash
# script to find and close ghost windows

ghost_window_ids=$(aerospace list-windows --all | grep -e '.*|.*| $' | awk '{print $1}')

for id in $ghost_window_ids ; do
    aerospace close --window-id $id
done
```

**Reply by PaulvSchaik** [reply]
These 2 work great @mblarsen @fozyus ! Thanks!

**Reply by naserowaimer** [reply]
> I have written this one
> 
> ```
> #!/bin/bash
> # script to find and close ghost windows
> 
> ghost_window_ids=$(aerospace list-windows --all | grep -e '.*|.*| $' | awk '{print $1}')
> 
> for id in $ghost_window_ids ; do
>     aerospace close --window-id $id
> done
> ```

This doesn't worked for me by pasting it in terminal. and because I don't want to make a lot of sh files, i prefer to bind shortcuts to run a command as is from the aerospace.toml. I have made this which will work always, it focus's in the ghost window and then close it. worked amazingly fine.
```
aerospace list-windows --all \
  | awk -F '|' 'NF < 3 || $3 ~ /^[[:space:]]*$/' \
  | awk '{print $1}' \
  | while read -r id; do
      echo "Trying to close ghost window ID: $id"
      aerospace focus --window-id "$id"
      aerospace close
  done
```

**Comment by amantinband** [comment]
EDIT: This issue is unrelated to aerospace
----

Okay so I did some more testing and seems like (for me) this is the status:

## Works
*  Switching node orientation: 'layout tiles horizontal vertical'
* Switching node orientation 'layout accordion horizontal vertical'
* Resizing tiles: 'resize smart'
* Switching between workspaces: 'workspace'

## Doesn't work
* Fullscreening a node: 'fullscreen'
* Moving nodes between workspaces: 'move-node-to-workspace'
* Moving focus between nodes: 'focus'

## Version
╰─ aerospace -v
aerospace CLI client version: 0.18.5-Beta 4213dfd9d958dbfe3f801e07d7d5af53303baa75
AeroSpace.app server version: 0.18.5-Beta 4213dfd9d958dbfe3f801e07d7d5af53303baa75

## Environment details
Machine: M4 Pro Max
OS: maxOS Tahoe 26.0 Beta (25A5279m)

This is my full config for reference

<details>

```toml
# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'




# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    ctrl-shift-s = 'layout tiles horizontal vertical'
    ctrl-shift-a = 'layout accordion horizontal vertical'
    ctrl-shift-m = 'fullscreen'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    ctrl-shift-h = 'focus left'
    ctrl-shift-j = 'focus down'
    ctrl-shift-k = 'focus up'
    ctrl-shift-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    cmd-ctrl-h = 'move left'
    cmd-ctrl-j = 'move down'
    cmd-ctrl-k = 'move up'
    cmd-ctrl-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    ctrl-1 = 'workspace 1'
    ctrl-2 = 'workspace 2'
    ctrl-3 = 'workspace 3'
    ctrl-4 = 'workspace 4'
    ctrl-5 = 'workspace 5'
    ctrl-6 = 'workspace 6'
    ctrl-7 = 'workspace 7'
    ctrl-8 = 'workspace 8'
    ctrl-9 = 'workspace 9'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    ctrl-shift-1 = 'move-node-to-workspace 1'
    ctrl-shift-2 = 'move-node-to-workspace 2'
    ctrl-shift-3 = 'move-node-to-workspace 3'
    ctrl-shift-4 = 'move-node-to-workspace 4'
    ctrl-shift-5 = 'move-node-to-workspace 5'
    ctrl-shift-6 = 'move-node-to-workspace 6'
    ctrl-shift-7 = 'move-node-to-workspace 7'
    ctrl-shift-8 = 'move-node-to-workspace 8'
    ctrl-shift-9 = 'move-node-to-workspace 9'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    ctrl-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    h = ['join-with left', 'mode main']
    j = ['join-with down', 'mode main']
    k = ['join-with up', 'mode main']
    l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
```

</details>
