### DISCUSSION TITLE
How about making "focus right" can go over monitor? (focus-monitor right)

### DISCUSSION THREAD

**Discussion by snova-paulk** [nikitabobko/AeroSpace#654] [questions-and-answers] [answered]
When I use `i3`, it was really convenient that  "focus right" can go beyond monitor.
For example, with `<alt> + arrow keys`, I was able to traverse any window in several monitors. 
In `aerospace`, `focus` only works in a monitor, and you'll need `focus-monitor` to go beyond. I think it's quite cumbersome. 

Can we make it happen?

**Comment by hpfmn** [comment]
I think it would help if `aerospace focus right` (and left/up/down) would report a negative return code if the end of the screen is reached. Then something like `exec-and-forget aerospace focus right || aerospace focus-monitor right` would work!

**Comment by gldtn** [comment, marked as answer]
I believe you are looking for this?:

```toml
# focus
alt-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
alt-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
alt-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
alt-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'
```
