### DISCUSSION TITLE
Numpad bindings?

### DISCUSSION THREAD

**Discussion by nickawilliams** [nikitabobko/AeroSpace#673] [questions-and-answers] [answered]
Is it possible to specify bindings for numpad keys that are separate from the number row keys?

example:

```toml
alt-2 = "workspace 2"
alt-num2 = "move down" # or whatever notation would reference 2 on a keyboard's numpad
```

**Comment by nickawilliams** [comment, marked as answer]
Ah nevermind, figured it out. For reference, just prefix a number with "keypad" like this:

```toml
alt-keypad8 = "move up"
alt-keypad2 = "move down"
alt-keypad4 = "move left"
alt-keypad6 = "move right"
```
