### DISCUSSION TITLE
Monitors have distinct workspaces

### DISCUSSION THREAD

**Discussion by aba-wtag** [nikitabobko/AeroSpace#717] [questions-and-answers]
I am a big fan of `AeroSpace` in Mac. I have previously used i3wm, hyperland and a big fan of DWM. 

In DWM, you get separate workspaces (1 - 9) for different monitors. For example, if you have two monitor then for monitor 1 you will have (1 - 9) workspaces and the same for monitor 2.

In `AeroSpace` I am trying to achieve the similar thing but don't know how to achieve this. Please let me know how to approach this problem if it is actually doable.

**Comment by alextremblay** [comment]
Aerospace has, by design, a shared pool of workspaces, any of which can be assigned to any monitor (exclusively, meaning same workspace can't be on multiple monitors at the same time)

I'm no expert, but i think you could accomplish something similar to what you're looking for with named workspaces and `workspace-to-monitor-force-assignment`

ie something like this:
```toml
a1 = 'monitor 1'
a2 = 'monitor 1'
a3 = 'monitor 1'
a4 = 'monitor 1'
a5 = 'monitor 1'
...
b1 = 'monitor 2'
b2 = 'monitor 2'
b3 = 'monitor 2'
b4 = 'monitor 2'
b5 = 'monitor 2'
...
c1 = 'monitor 3'
c2 = 'monitor 3'
c3 = 'monitor 3'
c4 = 'monitor 3'
c5 = 'monitor 3'
```

**Comment by ok-nick** [comment]
I'm looking for this feature as well. Something where all monitors share the same pool of workspaces 1-9, and you can switch to any of them on any monitor. If a workspace is already open on one monitor, then it will swap workspaces or focus that monitor. Maybe this feature deserves an issue?

**Reply by ok-nick** [reply]
UPDATE: The `summon-workspace` command kind of gets there. The only thing that feels weird is the behavior when you're focused on the main monitor vs external monitor, I'd expect it to be the same.

With this command, when you're focused on the main monitor and the workspace you're moving to is on an external monitor, it replaces the workspace on the main monitor. On the other hand, if you're focused on an external monitor and select a workspace that's already on another monitor, it will move to that monitor, which is the behavior I'd expect everywhere.

EDIT: https://github.com/nikitabobko/AeroSpace/discussions/737

**Comment by shipurjan** [comment]
I would also love to have the dwm-like behavior. 
I like to have 9 workspaces per monitor:
- when I'm focused on monitor 1, I can switch between 9 workspaces only on that monitor
- when I'm focused on monitor 2, ditto
- etc.

So for N monitors and M workspaces, the total number of workspaces would be NxM

**Reply by shipurjan** [reply]
I achieved this with the following config
It's probably bad practice to use exec-and-foget on aerospace commands like that but it works. Maybe there's a better way
```toml
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+0))'
alt-2 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+1))'
alt-3 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+2))'
alt-4 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+3))'
alt-5 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+4))'
alt-6 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+5))'
alt-7 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+6))'
alt-8 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+7))'
alt-9 = 'exec-and-forget aerospace workspace $(($(aerospace list-workspaces --monitor focused | head -1)+8))'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+0))'
alt-shift-2 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+1))'
alt-shift-3 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+2))'
alt-shift-4 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+3))'
alt-shift-5 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+4))'
alt-shift-6 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+5))'
alt-shift-7 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+6))'
alt-shift-8 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+7))'
alt-shift-9 = 'exec-and-forget aerospace move-node-to-workspace $(($(aerospace list-workspaces --monitor focused | head -1)+8))'

[workspace-to-monitor-force-assignment]
# Monitor 1
1 = '^lg.*ultrafine.*2'
2 = '^lg.*ultrafine.*2'
3 = '^lg.*ultrafine.*2'
4 = '^lg.*ultrafine.*2'
5 = '^lg.*ultrafine.*2'
6 = '^lg.*ultrafine.*2'
7 = '^lg.*ultrafine.*2'
8 = '^lg.*ultrafine.*2'
9 = '^lg.*ultrafine.*2'
# Monitor 2
10 = '^lg.*ultrafine.*1'
11 = '^lg.*ultrafine.*1'
12 = '^lg.*ultrafine.*1'
13 = '^lg.*ultrafine.*1'
14 = '^lg.*ultrafine.*1'
15 = '^lg.*ultrafine.*1'
16 = '^lg.*ultrafine.*1'
17 = '^lg.*ultrafine.*1'
18 = '^lg.*ultrafine.*1'
# Monitor 3
19 = '^studio.*display'
20 = '^studio.*display'
21 = '^studio.*display'
22 = '^studio.*display'
23 = '^studio.*display'
24 = '^studio.*display'
25 = '^studio.*display'
26 = '^studio.*display'
27 = '^studio.*display'
```
