### DISCUSSION TITLE
Compatibility with Displaylink

### DISCUSSION THREAD

**Discussion by seve** [nikitabobko/AeroSpace#728] [questions-and-answers] [answered]
Hi, I'm currently utilizing Display Link to enable multiple external monitors on my MBP w/ Apple Silicon. Does anyone have any experience using AeroSpace alongside Display Link?

**Comment by alextremblay** [comment, marked as answer]
wow, amazing timing! This is my first time visiting the aerospace discussions tab, and I'm exactly who you're looking for

short answer: yes. I have an M1 mac, using the built-in retina display and two external monitors hooked up through displaylink for a 3-monitor setup. I've been using Aerospace for a few days now, and it works flawlessly.

In fact, it fixes the biggest issue i had with yabai + displaylink + using a KVM to switch my monitors from my mac to my windows machine:

yabai organizes everything related to monitors (moving, focusing, etc) around display indexes (ie display 1, 2, 3, etc). Every time i switched the KVM, the displaylink monitors would disappear from the mac, all the spaces on them would get moved to the retina screen, and when i switched back, Displaylink would reinitialize them in a different order. As far as the mac was concerned, the monitors were still in the same arrangement, and moving the mouse from one ot the other would still work consistently, but because the monitor indexes were different, yabai keybinds for moving focus / window to the next or prev monitor would get all borked

Another issue that aerospace fixed for me with multiple monitors on a KVM through displaylink is that every time I'd switch my KVM back to my mac, all of my spaces (monitors have separate spaces enabled) would be placed on the wrong monitor and I'd have to click and drag them all back onto the correct monitor

Honestly, Spaces handling on MacOS with multiple monitors that frequently disappear and reappear is just a mess.

Aerospace's workspaces work much better.

In my aerospace config, i have named workspaces mapped to specific monitors. as soion as these monitors reappear in displaylink, aerospace automatically moves these workspaces back onto them, regardless of which order they reappear in:

```toml
[workspace-to-monitor-force-assignment]
# You can assign workspaces to monitors by their names or by their patterns.
# Monitor pattern is a case-insensitive substring of the monitor name.
code = ['lg', 'secondary']
web = ['lg', 'secondary']
other = ['lg', 'secondary']
chat = 'dell'
reference = 'dell'
mail = 'built-in'
```
