### DISCUSSION TITLE
Exec and forget doesn't seem to work

### DISCUSSION THREAD

**Discussion by Aryan3212** [nikitabobko/AeroSpace#739] [questions-and-answers]
**Describe the bug**
I have a script where I reset all the windows to their dedicated workspaces and then on a keybind use exec and forget to run that script. That script runs fine in the shell. However, in Aerospace it doesn't work.

Here's my config
```toml
# Commands to run after login
after-login-command = [

]

# Commands to run after AeroSpace startup
after-startup-command = [
    # 'osascript -e "tell application \\"Visual Studio Code\\" to activate"',
]

# Start AeroSpace at login
start-at-login = true

# Enable normalization rules
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layout and orientation settings
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus on monitor change
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

on-focus-changed = ['move-mouse monitor-lazy-center']

# Disable macOS "Hide Application" (Cmd + H)
# automatically-unhide-macos-hidden-apps = false
[exec.env-vars]
SHELL = '/bin/bash'

# Key mapping preset
[key-mapping]
preset = 'qwerty'

# Gaps settings
[gaps]
outer.bottom =        [{monitor.'^built-in retina display$' = 10 }, 10]
outer.top =        [{monitor.'^built-in retina display$' = 20 }, 52]
outer.left =       13
outer.right =      13
inner.horizontal = 10
inner.vertical =   10

# Binding Modes - Main mode
[mode.main.binding]
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# Application shortcuts
alt-enter = '''exec-and-forget osascript -e '
tell application "Wezterm"
    do script
    activate
end tell'
'''

# Layout shortcuts
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Focus navigation shortcuts
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move window shortcuts
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-i = 'exec-and-forget /Users/aryan.rahman/aerospace.sh'


# Resize window shortcuts
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace --auto-back-and-forth 1'
alt-2 = 'workspace --auto-back-and-forth 2'
alt-3 = 'workspace --auto-back-and-forth 3'
alt-4 = 'workspace --auto-back-and-forth 4'
alt-5 = 'workspace --auto-back-and-forth 5'
alt-6 = 'workspace --auto-back-and-forth 6'
alt-7 = 'workspace --auto-back-and-forth 7'
alt-8 = 'workspace --auto-back-and-forth 8'
alt-9 = 'workspace --auto-back-and-forth 9'
alt-a = 'workspace --auto-back-and-forth Browser:Personal' # In your config, you can drop workspace bindings that you don't need
alt-e = 'workspace --auto-back-and-forth Email'
alt-w = 'workspace --auto-back-and-forth Browser:Work'
alt-t = 'workspace --auto-back-and-forth Terminal'
alt-c = 'workspace --auto-back-and-forth code_editor'
alt-f = 'fullscreen'
alt-n = 'workspace --auto-back-and-forth Notes'

alt-m = 'workspace --auto-back-and-forth Messaging'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-a = 'move-node-to-workspace Browser:Personal' # In your config, you can drop workspace bindings that you don't need
alt-shift-e = 'move-node-to-workspace Email'
alt-shift-w = 'move-node-to-workspace Browser:Work'
alt-shift-t = 'move-node-to-workspace Terminal'
alt-shift-c = 'move-node-to-workspace code_editor'
alt-shift-n = 'move-node-to-workspace Notes'
alt-shift-m = 'move-node-to-workspace Messaging'

# Workspace back and forth
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Special mode: Service
alt-shift-semicolon = 'mode service'

# Service mode bindings
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

# Application assignments to workspaces

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace code_editor']

[[on-window-detected]]
if.workspace = '6'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['layout tiling', 'move-node-to-workspace Browser:Personal']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['layout tiling', 'move-node-to-workspace Terminal']
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace Notes']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = [
'layout floating'
]

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = [
'layout floating'
]

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'              
run = ['move-node-to-workspace Messaging']  

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'              
run = ['move-node-to-workspace Email']  


[[on-window-detected]]
if.app-id = 'com.microsoft.edgemac'              
run = ['move-node-to-workspace Browser:Work']  

[[on-window-detected]]
check-further-callbacks = true
run = ['layout floating', 'move-node-to-workspace 6']  
# Notify SketchyBar about workspace changes (Optional)
# exec-on-workspace-change = [
#     '/bin/bash', '-c',
#     'sketchybar --trigger aerospace_workspace_change FOCUSED=$AEROSPACE_FOCUSED_WORKSPACE'
# ]

```

I've tried setting execution environment still doesn't work. The command is alt-shift-i

**Related issues you could find**
Please make sure to search for duplicates.
If you couldn't find the duplicates, linking related issues is helpful anyway.
