### DISCUSSION TITLE
Set apps to a specific window size/position?

### DISCUSSION THREAD

**Discussion by cdog2020** [nikitabobko/AeroSpace#800] [questions-and-answers]
I know that you can automatically move specified apps to a workspace but is there a way to have it automatically set apps to a specific window size?  It would be awesome to have the ability to have this be automated instead of using `option+shift+ -/+`.  Thanks in advance!

**Comment by stonematt** [comment]
Agree.

I use SplashID as my password manager, when it opens, I get a password dialog, and then the app loads.  When I try to set it to float, it floats somewhere off screen.  How do I reset float to center?

Here's my config right now:

``` toml
# floating apps
[[on-window-detected]]
if.app-name-regex-substring = 'SplashID'
run = 'layout floating'
```

Here's how the app appears:
```
mstone@~
➜ aerospace list-windows --workspace 1 | rg Splash
6371 | SplashID Safe | SplashID Safe - mstone@stonecover.com
mstone@~
➜ aerospace list-apps |rg splash
87184 | com.splashdata.splashidmac | SplashID Safe
```

Any ideas?
