### DISCUSSION TITLE
Can we pause key listening?

### DISCUSSION THREAD

**Discussion by luisggc** [nikitabobko/AeroSpace#801] [questions-and-answers]
Do we have an option to pause key listening? Sometimes I have conflicts, so It would be nice to have something like:
stop listening shortcut => stop listening for all shortcuts in aerospace except the "start listening"
Aerospace shortcuts will not work anymore
start listening shortcut => all back to normal

Thanks for your time!

**Comment by Dimentium** [comment]
> Do we have an option to pause key listening? Sometimes I have conflicts, so It would be nice to have something like:
> 
> stop listening shortcut => stop listening for all shortcuts in aerospace except the "start listening"
> 
> Aerospace shortcuts will not work anymore
> 
> start listening shortcut => all back to normal
> 
> 
> 
> Thanks for your time!

Just define the separate mode:


````toml
[mode.main.binding]
# all your bindings are here
ctrl-cmd-alt-q = 'mode disabled'
[mode.disabled.binding]
ctrl-cmd-alt-q = 'mode main'
```
