### DISCUSSION TITLE
Startup application (default workspaces)

### DISCUSSION THREAD

**Discussion by ramonvermeulen** [nikitabobko/AeroSpace#807] [questions-and-answers] [answered]
Is it possible to save workspaces and use them as default? E.g. in i3 I had a set-up where certain applications went into certain workspaces (1-9) by default when booting my machine.

**Comment by rollsrobby** [comment, marked as answer]
Maybe you can combine `after-login-command = []` with on-window-detect.

```toml
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['move-node-to-workspace T']
```
I use a shortcut to start the apps to not have this open everytime I boot.
