### DISCUSSION TITLE
Resize to relative screen size

### DISCUSSION THREAD

**Discussion by domvo** [nikitabobko/AeroSpace#839] [feature-ideas] [answered]
I would like a command that lets me resize a window to 1/3 of the screen and inversely the other one to 2/3. Since I work with different external monitors (with different resolutions) relative instead of absolute numbers would be great.

If this is already achievable I would appreciate a cue into the right direction.

**Comment by incanus** [comment]
I'm not seeing this, other than using an external keybinding tool to do the calculation based on screen width (example: Hammerspoon) and then calling `aerospace resize width X` from that.

**Reply by incanus** [reply]
Building off of this, I made a quick-and-dirty script called `~/bin/aerowidth.sh` that looks like this: 

```bash
#!/usr/bin/env sh

WIDTH=$(osascript -e 'tell app "Finder" to get bounds of window of desktop' | sed -e 's/0, 0, //' -e 's/, .*//')

if [ $1 == 1 ]; then
  TARGET=$(bc -e "$WIDTH / 3")
elif [ $1 == 2 ]; then
  TARGET=$(bc -e "$WIDTH / 2")
elif [ $1 == 3 ]; then
  TARGET=$(bc -e "2 * $WIDTH / 3")
fi

aerospace resize width $TARGET
```

Then I call it with these keybindings: 

```toml
alt-cmd-1 = 'exec-and-forget ~/bin/aerowidth.sh 1'
alt-cmd-2 = 'exec-and-forget ~/bin/aerowidth.sh 2'
alt-cmd-3 = 'exec-and-forget ~/bin/aerowidth.sh 3'
```

This binds these to current window to 1/3, 1/2, or 2/3 of the current screen width.
