### DISCUSSION TITLE
Web Browser PiP stop from being affected

### DISCUSSION THREAD

**Discussion by TaylorJonesTRT** [nikitabobko/AeroSpace#916] [questions-and-answers] [answered]
Is there a way to stop the Firefox/Zen browsers PiP feature from being managed by Aerospace? I want the pip player to be able to hover without having to do the alt+shift+; ... f command on it every time.

**Comment by lighterless** [comment, marked as answer]
Add this to your config

```toml
[[on-window-detected]]
if.app-id                       = 'org.mozilla.firefox'
if.window-title-regex-substring = 'Picture-in-Picture'
run                             = 'layout floating'
```
