### DISCUSSION TITLE
Multiple configs for different screen setups

### DISCUSSION THREAD

**Discussion by cem-al** [nikitabobko/AeroSpace#945] [feature-ideas]
I use a laptop at work which is plugged into a monitor, otherwise I use my laptop screen.

Currently I comment part of my config depending on the location:

```toml
# Desktop

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'  # WezTerm
run = 'move-node-to-workspace 1'       # Terminal workspace

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'      # Firefox
run = 'move-node-to-workspace 1'       # Browser workspace

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'        # Figma
run = 'move-node-to-workspace 2'       # Design workspace

[[on-window-detected]]
if.app-id = "net.whatsapp.WhatsApp"
run = 'move-node-to-workspace 3'       # Communication workspace

[[on-window-detected]]
if.app-id = 'com.cron.electron'        # Calendar
run = 'move-node-to-workspace 4'       

[[on-window-detected]]
if.app-id = 'com.spotify.client'        # Spotify
run = 'move-node-to-workspace 5'       # Design workspace

# Laptop

# [[on-window-detected]]
# if.app-id = 'com.github.wez.wezterm'  # WezTerm
# run = 'move-node-to-workspace 1'       # Terminal workspace

# [[on-window-detected]]
# if.app-id = 'org.mozilla.firefox'      # Firefox
# run = 'move-node-to-workspace 2'       # Browser workspace

# [[on-window-detected]]
# if.app-id = 'com.figma.Desktop'        # Figma
# run = 'move-node-to-workspace 3'       # Design workspace

# [[on-window-detected]]
# if.app-id = "net.whatsapp.WhatsApp"
# run = 'move-node-to-workspace 4'       # Communication workspace

# [[on-window-detected]]
# if.app-id = 'com.cron.electron'        # Calendar
# run = 'move-node-to-workspace 5'       

# [[on-window-detected]]
# if.app-id = 'com.spotify.client'        # Spotify
# run = 'move-node-to-workspace 6'       # Design workspace
```

and then run :

`bash
osascript -e 'quit app "AeroSpace"' && open -a AeroSpace
`

It would be great to have a way of switiching layouts, or configs.
