### DISCUSSION TITLE
`workspace` command should focus the monitor containing the specified workspace

### DISCUSSION THREAD

**Discussion by ok-nick** [nikitabobko/AeroSpace#950] [potential-bugs]
Hi, I'd like to be able to focus a workspace on a separate monitor, and for the focus to move to that monitor. Additionally, if a workspace is focused that is not assigned to a monitor, it should stay on the current monitor and move to that workspace. The current behavior will switch focus to the main monitor and then switch the workspace, which is a bit unintuitive in a multi-monitor setup.

**Comment by nikitabobko** [comment]
It already should work the way you describe it. If it doesn't - it's a bug.

1. Is the workspace that you're trying to switch to empty?
2. How do you manage your workspace switching hotkeys? Via AeroSpace or skhd? Or please better share your config

**Reply by ok-nick** [reply]
> 1. Is the workspace that you're trying to switch to empty?

It doesn't matter if there is or isn't a window, the same behavior occurs.

> 2. How do you manage your workspace switching hotkeys? Via AeroSpace or skhd? Or please better share your config

Via Aerospace.

<details>
<summary>Here is my full config:</summary>

```toml
accordion-padding = 30
after-login-command = []
after-startup-command = []
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = false
exec-on-workspace-change = []
on-focus-changed = []
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
start-at-login = false

[key-mapping]
preset = "qwerty"

[mode.main.binding]
alt-0 = "workspace 10"
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
alt-b = "balance-sizes"
alt-f = "fullscreen"
alt-h = "focus --boundaries all-monitors-outer-frame left"
alt-j = "focus --boundaries all-monitors-outer-frame down"
alt-k = "focus --boundaries all-monitors-outer-frame up"
alt-l = "focus --boundaries all-monitors-outer-frame right"
alt-period = "layout accordion"
alt-shift-0 = "move-node-to-workspace 10"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"
alt-shift-down = "move down"
alt-shift-equal = "resize smart +50"
alt-shift-f = "macos-native-fullscreen"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-left = "move left"
alt-shift-minus = "resize smart -50"
alt-shift-right = "move right"
alt-shift-space = "layout floating tiling"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-shift-up = "move up"
alt-shift-w = "mode service"
alt-slash = "layout tiles"
alt-tab = "workspace-back-and-forth"
alt-v = "layout horizontal vertical"
cmd-alt-h = []
cmd-h = []

[mode.service.binding]
alt-shift-down = ["join-with down", "mode main"]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]
alt-shift-left = ["join-with left", "mode main"]
alt-shift-right = ["join-with right", "mode main"]
alt-shift-up = ["join-with up", "mode main"]
```

</details>
