### DISCUSSION TITLE
Support for azerty keyboards

### DISCUSSION THREAD

**Discussion by KevinFalzone** [nikitabobko/AeroSpace#976] [feature-ideas]
Hello,

Is it possible to add the azerty configuration to Aerospace?

"
# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'
"

In addition, numbers and signs are reversed on azerty keyboards.

Here's an illustration:
https://www.journaldulapin.com/wp-content/uploads/2017/12/02-2.png

Also for azerty windows keyboards the configuration is as follows:
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/KB_France.svg/1000px-KB_France.svg.png

Can we add the following signs :
| N   | APPLE   | Windows   |
| --- | ------- | --------- |
| 1   | &       | &         |
| 2   | é       | é         |
| 3   | "       | "         |
| 4   | '       | '         |
| 5   | (       | (         |
| 6   | §       | -         |
| 7   | è       | è         |
| 8   | !       | _         |
| 9   | ç       | ç         |
| 0   | à       | à         |
| --- | ------- | --------- |

Thanks in advance.

**Comment by Ga13Ou** [comment]
Is it possible to have this preset added ?

**Comment by GllmR** [comment]
Do we have a way to find the name of a key ?

In Hyprland, it's named like this:
```
# ~/.config/hypr/hyprland.conf
# Switch workspaces with mainmod + [0-9]
bind = $mainmod, ampersand, workspace, 1
bind = $mainmod, eacute, workspace, 2
bind = $mainmod, quotedbl, workspace, 3
bind = $mainmod, apostrophe, workspace, 4
bind = $mainmod, parenleft, workspace, 5
bind = $mainmod, minus, workspace, 6
bind = $mainmod, egrave, workspace, 7
bind = $mainmod, underscore, workspace, 8
bind = $mainmod, ccedilla, workspace, 9
bind = $mainmod, agrave, workspace, 10
```

**Comment by nikitabobko** [comment]
As someone who doesn't use azerty, the issue is unclear. I'm looking at the picture: https://en.wikipedia.org/wiki/AZERTY

and I don't understand why placing the following in the config, won't resolve the problem
```toml
[key-mapping.key-notation-to-key-code]
    '&' = '1'
    'é' = '2'
    '"' = '3'
    "'" = '4'
    '(' = '5'
    '§' = '6'
    'è' = '7'
    '!' = '8'
    'ç' = '9'
    'à' = '0'
    ')' = '-'
    '-' = '='

    a = 'q'
    z = 'w'
    e = 'e'
    r = 'r'
    t = 't'
    y = 'y'
    u = 'u'
    i = 'i'
    o = 'o'
    p = 'p'
    '^' = 'leftSquareBracket'
    '$' = 'rightSquareBracket'

    q = 'a'
    s = 's'
    d = 'd'
    f = 'f'
    g = 'g'
    h = 'h'
    j = 'j'
    k = 'k'
    l = 'l'
    m = 'semicolon'
    'ù' = 'quote'

    w = 'z'
    x = 'x'
    c = 'c'
    v = 'v'
    b = 'b'
    n = 'n'
    comma = 'm'
    semicolon = 'comma'
    colon = 'period'
    '=' = 'slash'
```
