### ISSUE TITLE
Feature request: introduce `if.is-dialog` in `on-window-detected` callback

### ISSUE THREAD

**Issue by nikitabobko** [nikitabobko/AeroSpace#103]
Users tend to write callbacks like this:
```toml
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 2'
```

The problem with callbacks like this is that if during the work, users move the window to a different workspace, and then decide to open some dialog, the dialog will be moved back to workspace 2

It would be nice to make it possible to ignore these callbacks for dialogs. 

1. One way of doing this could be to introduce `if.is-dialog`. The problem with this solution is that it is not "enabled" by default. Users would need to remember that they always need to write `if.is-dialog = false`
2. Another crazy solution could be to introduce an option for `move-node-to-workspace` command `[--if-dialog [no]]`. And say that `--if-dialog no` is enabled by default in `on-window-detected` callback
