### ISSUE TITLE
Add `automatically-unhide-macos-hidden-apps-exceptions = [...]` config option

### ISSUE THREAD

**Issue by nikitabobko** [nikitabobko/AeroSpace#1041]
The proposal:
```toml
automatically-unhide-macos-hidden-apps = true
automatically-unhide-macos-hidden-apps-exceptions = ['com.github.wez.wezterm']
```

1. Apps in the list should be excluded from the `automatically-unhide-macos-hidden-apps` logic.
2. Specifying non-empty `automatically-unhide-macos-hidden-apps-exceptions` array while `automatically-unhide-macos-hidden-apps = false` should be config error

Use cases:
1. Discord app is misbehaving. Instead of closing windows for real, it uses "hide app" when you try to close its window
2. Raycast supposedly uses "hide app" to toggle windows https://github.com/nikitabobko/AeroSpace/discussions/1040
