### ISSUE TITLE
Add command to programatically run all on-window-detected callbacks 

### ISSUE THREAD

**Issue by carlosflorencio** [nikitabobko/AeroSpace#107]
Hi,

It's possible to have a command that runs all the `on-window-detected` callbacks?

Use-case:
I have the apps <> workspaces affinities setup like:

```
# apps to workspaces
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi'
run = ['move-node-to-workspace 2']

...
```

Sometimes I move apps between workspaces and then have the need to reposition them back to the initial workspaces. So it would be useful to have a command like `aerospace force-window-detected` to run all the rules the move the windows back to their original workspace.

Also a different request question, it's possible to assign layouts to workspaces in the config file? e.g `workspace 1` to start with the `h_accordion` layout.

**Comment by nikitabobko** [comment]
> So it would be useful to have a command like aerospace force-window-detected to run all the rules the move the windows back to their original workspace.

Nice. I like the suggestion. The hardest part here is to come up with a good name for the command

Brainstorming:
1. `force-window-detected` (the suggested name)
2. `run-on-window-detected-callbacks` 
3. `force-run-on-window-detected-callbacks`
4. `redetect-windows`

Right now, 2 and 3 are my favorite. IMO, they are the most clear. Ideas are welcome

> Also a different request/question, it's possible to assign layouts to workspaces in the config file? e.g workspace 1 to start with the h_accordion layout.

Right now. it's not possible, but probably it'd be nice to have. What is your use case? 

I'm curious if it were possible to run `layout` command in `on-window-detected` callback, would it resolve your issue? (this way you will apply the layout only if the specific window is detected, but maybe it's exactly what you want to, I don't know your use cases)

The hardest part is to come up with a good syntax

Brainstorming:
**(1)**
```toml
default-root-container-layout = 'tiles'
workspace.1.default-root-container-layout = 'tiles'
```
**(2)**
```toml
[default-root-container-layout]
workspace.1 = 'tiles'
workspace.2 = 'accordion'
workspace.all = 'tiles' # 'all' will be a reserved name for workspaces since 0.8.0, anyway
```
**(3)**
```toml
[default-root-container-layout]
workspace.1 = 'tiles'
workspace.2 = 'accordion'
other = 'tiles'
```
