### ISSUE TITLE
Focus previous window after closing the child

### ISSUE THREAD

**Issue by EmpathyZeroed** [nikitabobko/AeroSpace#1086]
**How to make AeroSpace to focus the previous window after a child window was closed?**

i.e. I've opened an image in Preview from Finder, when I close Preview - instead of focusing Finder's image folder it randomly selects a random app inside the current workspace

Repro:
1. Open a workspace with N apps in it + Finder. All in floating mode
2. Open Finder
3. Navigate a folder with images
4. Open an image (with Preview)
5. Close an image (CTRL + W)
6. Focus randomly selects an app from the current workspace, not the parent Finder window which the Preview was launched from from

**Comment by EmpathyZeroed** [comment]
@nikitabobko I guess the solution would be to add variable assignment with ID of the window on focus_changed event similar to exec-on-workspace-change variables, i.e.
```
AEROSPACE_FOCUSED_WINDOW_ID - the window ID user switched to
AEROSPACE_PREV_WINDOW_ID - the window ID user switched from
```

in https://github.com/nikitabobko/AeroSpace/blob/2f0c1739b58c8a196b1bc8d922c8d7c6054b90b7/Sources/AppBundle/focus.swift#L164

Also somewhat similar issue #https://github.com/nikitabobko/AeroSpace/issues/509

**Comment by DevER-M** [comment]
hey @EmpathyZeroed did you find a solution for this issue?

**Comment by EmpathyZeroed** [comment]
> hey [@EmpathyZeroed](https://github.com/EmpathyZeroed) did you find a solution for this issue?

nope, I'm unsure that even if the dev reacts it will be in near future release. #5 they're still considering if it worth adding lol so I guess the only way is to make a patch and build fixed aerospace yourself, my solution is above. I want to believe that I might be just stupid and something wrong with my config but seems that it isn't

anyway, here it:

```toml
# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[exec]
    inherit-env-vars = true
[exec.env-vars]
    PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:${PATH}'


# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # alt-enter = '''exec-and-forget kitty --single-instance'''
    alt-f = 'layout floating tiling'

    cmd-h = [] # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -75'
    alt-equal = 'resize smart +75'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-1 = 'workspace MAIN'
    alt-2 = 'workspace HELP'
    alt-3 = 'workspace CODE'
    alt-4 = 'workspace AUX'
    alt-5 = 'workspace AUX2'
    alt-6 = 'workspace CHAT'
    alt-7 = 'workspace TERM'
    alt-8 = 'workspace PERS'
    alt-9 = 'workspace BG'
    alt-0 = 'workspace TEXT'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-shift-1 = 'move-node-to-workspace MAIN'
    alt-shift-2 = 'move-node-to-workspace HELP'
    alt-shift-3 = 'move-node-to-workspace CODE'
    alt-shift-4 = 'move-node-to-workspace AUX'
    alt-shift-5 = 'move-node-to-workspace AUX2'
    alt-shift-6 = 'move-node-to-workspace CHAT'
    alt-shift-7 = 'move-node-to-workspace TERM'
    alt-shift-8 = 'move-node-to-workspace PERS'
    alt-shift-9 = ['layout floating', 'move-node-to-workspace BG']
    alt-shift-0 = 'move-node-to-workspace TEXT'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-shift-up = 'move-workspace-to-monitor prev'
    alt-shift-down = 'move-workspace-to-monitor next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    b = ['balance-sizes', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']


# [workspace-to-monitor-force-assignment]
#     1 = 1                            # Monitor sequence number from left to right. 1-based indexing
#     2 = 'main'                       # Main monitor
#     3 = 'secondary'                  # Non-main monitor in case when there are only two monitors
#     4 = 'built-in'                   # Case insensitive regex substring
#     5 = '^built-in retina display$'  # Case insensitive regex match
#     6 = ['secondary', 'dell']        # You can specify multiple patterns.
#                                      #   The first matching pattern will be used


# kitty
[[on-window-detected]]
	if.app-name-regex-substring = 'kitty'
  run = 'layout floating'

# sublime
[[on-window-detected]]
	if.app-id = 'com.sublimetext.4'
	run = 'layout floating'

# telegram desktop
[[on-window-detected]]
	if.app-id = 'com.tdesktop.Telegram'
	run = 'layout floating'

# finder
[[on-window-detected]]
	if.app-id = 'com.apple.finder'
  run = 'layout floating'

# preview
[[on-window-detected]]
	if.app-id = 'com.apple.Preview'
  run = 'layout floating'

# quicktime
[[on-window-detected]]
	if.app-id = 'com.apple.QuickTimePlayerX'
  run = 'layout floating'

# iina
[[on-window-detected]]
	if.app-id = 'com.colliderli.iina'
  run = 'layout floating'

# chatgpt
[[on-window-detected]]
	if.app-id = 'com.openai.chat'
  run = 'layout floating'

# exodus
[[on-window-detected]]
	if.app-id = 'com.electron.exodus'
  run = 'layout floating'

# idle
[[on-window-detected]]
	if.app-id = 'org.python.IDLE'
	run = 'layout floating'

# activity moniitor 
[[on-window-detected]]
	if.app-id = 'com.apple.ActivityMonitor'
	run = 'layout floating'

# ---------------------------------

# all BG workspace
[[on-window-detected]]
  if.workspace = 'BG'
  run = 'layout floating'
  check-further-callbacks = true

# MAIN
[[on-window-detected]]
	if.app-id = 'org.mozilla.firefox'
	if.during-aerospace-startup = true
	run = ['layout tiling', 'move-node-to-workspace MAIN']

# HELP
[[on-window-detected]]
	if.app-id = 'xyz.chatboxapp.app'
	run = ['layout tiling', 'move-node-to-workspace HELP']

[[on-window-detected]]
	if.app-id = 'com.linguee.DeepLCopyTranslator'
	run = ['layout tiling', 'move-node-to-workspace HELP']

# CODE
[[on-window-detected]]
	if.app-id = 'com.microsoft.VSCode'
	if.during-aerospace-startup = true
	run = ['layout tiling', 'move-node-to-workspace CODE']

# CHAT
[[on-window-detected]]
	if.app-id = 'org.whispersystems.signal-desktop'
	run = ['layout tiling', 'move-node-to-workspace CHAT']

[[on-window-detected]]
	if.app-id = 'ru.keepcoder.Telegram'
	run = ['layout tiling', 'move-node-to-workspace CHAT']

[[on-window-detected]]
	if.app-id = 'im.riot.app'
	run = ['layout tiling', 'move-node-to-workspace CHAT']

# BG
[[on-window-detected]]
	if.app-id = 'e.AmneziaVPN'
  run = ['layout floating', 'move-node-to-workspace BG']

# TEXT
[[on-window-detected]]
	if.app-id = 'md.obsidian'
	# if.during-aerospace-startup = true
	run = ['layout tiling', 'move-node-to-workspace TEXT']

[[on-window-detected]]
	if.app-id = 'com.sublimetext.4'
	if.during-aerospace-startup = true
	run = ['layout tiling', 'move-node-to-workspace TEXT']
```
