### ISSUE TITLE
Question about on-window-detected callback and regexps

### ISSUE THREAD

**Issue by Coobaha** [nikitabobko/AeroSpace#127]
Hi @nikitabobko, thank you for the Aerospace! I really like it.

I have a small question regarding the appropriate approach for this configuration:

```toml
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
if.app-name-regex-substring = ' \[' # main project
run = 'move-node-to-workspace F'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
if.window-title-regex-substring = 'Update Project|Settings'
run = 'move-node-to-workspace F'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace W'  # secondary monitor
```

Is there a better version of doing this? At least this doesn't work, I assume it is because there in no negative lookahead in swift from strings?

```toml
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
if.window-title-regex-substring = '!(Update Project|Settings)'
run = 'move-node-to-workspace W' 
```
