### ISSUE TITLE
Feature: conditional bindings. Per-app bindings

### ISSUE THREAD

**Issue by nikitabobko** [nikitabobko/AeroSpace#1454]
## Description

Add an ability to define application specific bindings

The issue becomes even more relevant after the introduction of `menu-bar` command https://github.com/nikitabobko/AeroSpace/issues/1403

## Details

The design is yet unclear, but the feature request deserves a tracking issue (which this issue is about)

Very much related and should be designed together: https://github.com/nikitabobko/AeroSpace/issues/278

## Use cases

- per-app `menu-bar` command #1403 
- Swap alt/opt and cmd modifiers (not covered by the suggested drafts)

## Drafts

```toml
[[conditional]]
    if = 'test --app-bundle-id org.mozilla.firefox'
    [conditional.binding] # TOML is hell ugly
        ctrl-n = 'menu-bar --match-path-suffix "new tab" --click-first'
```

```toml
[mode.main.app-binding.org.mozilla.firefox]
    ctrl-n = 'menu-bar --match-path-suffix "new tab" --click-first'
```

```toml
[[mode.main.conditional-binding]] # Surprisingly it doesn't conflict with [mode.main.binding]
    if = 'test --app-bundle-id org.mozilla.firefox'
    ctrl-n = '...'
```

## Discarded alternatives

```toml
[mode.main.binding]
    ctrl-n = '''
        if test --app-bundle-id org.mozilla.firefox do
            menu-bar --match-path-suffix 'new tab' --click
        else
            pass
            # or: send-key ctrl-n
        end
    '''
```

Discarded because I am slowly moving away from the idea of introducing built-in control flow structures like `if`

```toml
[mode.main.binding]
    ctrl-n = { if = 'test --app-bundle-id org.mozilla.firefox', run = 'menu-bar --match-path-suffix "new tab" --click-first' }
```

Discarded because the syntax is misleading on when the binding swallows the key event

## Open questions

- The exact TOML syntax is an open question
- It'd be cool if modes somehow could cover the use case, but I don't see how

**Comment by richard134** [comment]
What if `mode.app.<bundle-id>` was a special namespace that auto-activates when that app is focused? Combined with an `inherits` key for modes, this could cover the use case while building on existing concepts.

```toml
[mode.main.binding]
alt-h = 'focus left'
alt-j = 'focus down'
alt-1 = 'workspace 1'

[mode.app.org.mozilla.firefox]
inherits = 'main'
binding.alt-t = 'menu-bar --match "New Tab" --click'
binding.alt-w = 'menu-bar --match "Close Tab" --click'

[mode.app.com.apple.finder]
inherits = 'main'
binding.alt-n = 'menu-bar --match "New Folder" --click'
```

You could also chain inheritance for app groups. For example, unified shortcuts across all browsers:

```toml
[mode.browsers]
inherits = 'main'
binding.alt-t = 'menu-bar --match "New Tab" --click'
binding.alt-w = 'menu-bar --match "Close Tab" --click'
binding.alt-l = 'menu-bar --match "Open Location" --click'

[mode.app.org.mozilla.firefox]
inherits = 'browsers'

[mode.app.com.google.Chrome]
inherits = 'browsers'

[mode.app.com.apple.Safari]
inherits = 'browsers'
# Safari uses a different menu item name
binding.alt-shift-t = 'menu-bar --match "Reopen Last Closed Tab" --click'
```

**Behavior:**

- When focus changes, AeroSpace checks if `mode.app.<bundle-id>` exists
- If yes, activate it automatically
- If no, stay in `main` (or current manual mode)
- Binding resolution walks the `inherits` chain

**Manual mode override:**

If a user manually enters a mode (e.g. `mode resize`) while in an auto-activated app mode, the manual mode takes precedence. When exiting back to `main`, the app-auto-mode kicks back in if that app is still focused.
