### ISSUE TITLE
Keynames for < and > sign in aerospace config

### ISSUE THREAD

**Issue by Kamyil** [nikitabobko/AeroSpace#155]
HI! Thank you so much for this repo, since I can finally use quick workspace switch like in i3 which I couldn't do with default slow transitions <3 I love the app so far

I have a question if I may ask. I've tried to find a solution for that but couldn't make it work
In my i3config I had a binding `Meta + Shift + >` or `Meta + Shift + <` to move workspace to either left or right monitor
https://github.com/Kamyil/.dotfiles/blob/9422d244a7e01ed68902b5244ffb8a44003a8acb/i3/config#L187

I've tried to replicate that shortcut in `aerospace.toml` file, but I couldn't find the keyname of `<` & `>`  keys that aerospace would parse. I've tried looking here
https://github.com/nikitabobko/AeroSpace/blob/main/src/config/keysMap.swift
and in referenced skhd source file, but couldn't find them there to

I've also tried blindly guessing the keyname with those keynames `less//greater`,  `lessThan/greaterThan`, `leftChevron/rightChevron` and didn't work

So in tl;dr: I would like to make these work

```toml
cmd-shift-lessThan = 'move-workspace-to-monitor --wrap-around prev'
cmd-shift-greaterThan = 'move-workspace-to-monitor --wrap-around next'
```

Extra info

```
aerospace CLI client version: 0.8.4-Beta 4951cbc3167737235c4dcf9c7521bd9a6418c699
AeroSpace.app server version: 0.8.4-Beta 4951cbc3167737235c4dcf9c7521bd9a6418c699

macOS Sonoma 14.2.1
```

My config so far:
```toml
# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
# alt-shift-t = 'exec-and-forget open -n /System/Applications/Alacritty.app'

alt-j = 'focus left'
alt-k = 'focus down'
alt-l = 'focus up'
alt-semicolon = 'focus right'

alt-h = 'split horizontal'
alt-v = 'split vertical'


# alt-f = 'fullscreen'
# alt-s = 'layout v_accordion' # 'layout stacking' in i3
# alt-w = 'layout h_accordion' # 'layout tabbed' in i3
# alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide.html#floating-windows
# alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 10'

cmd-shift-less = 'move-workspace-to-monitor --wrap-around prev'
cmd-shift-= 'move-workspace-to-monitor --wrap-around next'

alt-shift-c = 'reload-config'
alt-shift-f= 'layout floating tiling' # 'floating toggle' in i3
alt-shift-r = 'mode resize'
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l= 'move right'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
```
