### ISSUE TITLE
Define layouts in configuration file

### ISSUE THREAD

**Issue by ctruett** [nikitabobko/AeroSpace#187]
It would be helpful to be able to define layouts in the configuration that would be restore on launch or that could be triggered by a hotkey.

The layout definitions could look like this:

```toml
[layout]
name = 'main_workspace'
mode = 'tiling'
monitor = 1

[zones]

[zone.1]
type = 'v_accordion'
apps = ['com.apple.Safari.WebApp.F0204BE2-0E82-4F6D-B6C4-BE08613F04E9']
position = [8, 33]
size = [582, 1758]

[zone.2]
type = 'static'
apps = ['com.apple.Safari']
position = [602, 33]
size = [1492, 1758]

[zone.3]
type = 'tiles'
apps = ['com.googlecode.iTerm2']
position = [2106, 33]
size = [1086, 873]

[zone.4]
type = 'tiles'
apps = ['com.microsoft.teams2']
position = [2106, 918]
size = [1086, 873]
```
