### ISSUE TITLE
Launching alacritty via aerospace does not source .zshrc file

### ISSUE THREAD

**Issue by rmathews-eb** [nikitabobko/AeroSpace#199]
Hey there! I'm honestly not entirely sure if this issue is specific to aerospace but I have the following issue.

When I open Alacritty via finder/spotlight/launchpad it sources my .zshrc file and everything launches as expected. However if I run Alacritty via Aerospace's `exec-and-forget` command then the initial shell has not sourced the .zshrc file and I have to do so myself either by running `source ~/.zshrc` or spawning a nested shell by running `zsh` itself.

I thought this might be due to some env var thing so I tried toggling [exec-inherit-env-vars](https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars) on and off but this issue happens both ways.

My current config file is as follows...
```toml
# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
alt-enter = 'exec-and-forget open -n /System/Volumes/Data/Applications/Alacritty.app'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-f = 'fullscreen'

alt-w = 'close --quit-if-last-window'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-n = 'move-workspace-to-monitor --wrap-around next'

alt-shift-c = 'reload-config'

alt-shift-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
```
