### ISSUE TITLE
Feature: Implement sticky floating windows

### ISSUE THREAD

**Issue by nikitabobko** [nikitabobko/AeroSpace#2]
https://i3wm.org/docs/userguide.html#_sticky_floating_windows

**Comment by AlJohri** [comment]
Is it possible to have sticky non-floating windows? SImilar to this request: https://github.com/koekeishiya/yabai/issues/1843

I'd like to have a constant window on my screen as I flip through workspaces.

**Comment by nikitabobko** [comment]
"sticky sidebar" windows bring some challenges 

- What if users want to have several sticky sidebar windows
- What should happen if a sticky sidebar window is moved with the mouse?
  - Should it become a regular tiling window?
  - Or should it remain sticky sidebar?
- Should "sticky sidebar" windows be a per-monitor thing?
  - If the answer is yes, how users are supposed to move sticky sidebar window between monitors?
    - What should happen if users move a window to a monitor where another sticky sidebar windows is already presented?

But in general, I like the suggestion, I also always wanted to have sticky non-floating windows in i3

**Comment by nikitabobko** [comment]
Maybe we are better off with a feature like "virtual monitors". That way you could place two virtual monitors on your physical monitor. You could cycle workspaces only on one of those virtual monitors

**Comment by tngafwlehmann** [comment]
> Maybe we are better off with a feature like "virtual monitors". That way you could place two virtual monitors on your physical monitor. You could cycle workspaces only on one of those virtual monitors

That's indeed a great thing to have. For i3 I typically use xrandr to split up a 5120x? physical device into three virtual monitors, the latter of which can then be used for workspace assignments.

But this does not solve the issue for floating windows (assuming a certain preference for floating Zoom/Teams/etc. because it's easier to re-arrange during meetings). So I'd vote for both :)

**Comment by TC-MO** [comment]
Has this ever been implemented? I'm looking for a way to keep FF PiP window in the same position when moving workspaces

**Comment by farzadmf** [comment]
For now, I'm manually doing this when I switch workspaces:
- Before I switch; I search to see if there are any PIP windows
- I focus that window and move it to the target workspace (too bad `aerospace` doesn't let me do `move-node-to-workspace --window-id <window-id> <target-ws>` ... so sad 😔 )
- Then, I switch to the target workspace.

I must say, it's a very weird and terrible experience, but at least the PIP window is "sticky"! 😐

**Comment by gservat** [comment]
Would be super neat to keep a Zoom floating window as sticky so I can see whats going on in a meeting while I cycle through workspaces.

**Comment by bitskc** [comment]
I'm definitely in need of this feature!  Hope it comes soon!

**Comment by PaRr0tBoY** [comment]
Can we extend the functionality of exec-on-workspace-change,force specific windows to move-node-to-{{currently focused workspace}}?

**Comment by andsnpl** [comment]
I thought this would be possible to jury-rig for at least one window using `exec-on-workspace-change`, but I'm not having much success. My attempt, in case anyone can make it work:

```toml
exec-on-workspace-change = ['/bin/bash', '-c',
  'WIN=$(aerospace list-windows --all | grep "<Window Title>" | cut -d" " -f1); [ -n "$WIN" ] && aerospace move-node-to-workspace --window-id="$WIN" "$AEROSPACE_FOCUSED_WORKSPACE"'
]
```

**Comment by gservat** [comment]
@andsnpl: I think the issue with yours is the `=` after `--window-id`. This works:

```
exec-on-workspace-change = ['/bin/bash', '-c',
  'WIN=$(aerospace list-windows --all | grep "<Window Title>" | cut -d" " -f1); [ -n "$WIN" ] && aerospace move-node-to-workspace --window-id "$WIN" "$AEROSPACE_FOCUSED_WORKSPACE"'
]
```

However, it seemed to move the window to the focused workspace but it lost focus so it would be behind my other windows. I tried giving it focus as part of `exec-on-workspace-change` (see below), which kinda works (moves the window and gives it focus), but it's not really useable for my needs as clicking on any other window will send it to the back:

```
exec-on-workspace-change = ['/bin/bash', '-c',
  'WIN=$(aerospace list-windows --all | grep "<Window Title>" | cut -d" " -f1); [ -n "$WIN" ] && aerospace move-node-to-workspace --window-id "$WIN" "$AEROSPACE_FOCUSED_WORKSPACE" && aerospace focus --window-id "$WIN"'
]
```

**Comment by andsnpl** [comment]
Thanks for the feedback @gservat. It still doesn't work for me. I tried echoing the winId to a file:

```toml
exec-on-workspace-change = ['/bin/bash', '-c',
  # 'WIN=$(aerospace list-windows --all | grep "<Window Title>" | cut -d" " -f1); [ -n "$WIN" ] && aerospace move-node-to-workspace --window-id "$WIN" "$AEROSPACE_FOCUSED_WORKSPACE"'
  'WIN=$(aerospace list-windows --all | grep "<Window Title>" | cut -d" " -f1); echo "$WIN -> $AEROSPACE_FOCUSED_WORKSPACE" > "$HOME/Desktop/floating_window.txt"'
]
```

but the value printed is empty.

```
 -> G
```

This is the case no matter what window title I'm searching for. I wonder if there is something in my config that is causing the nested aerospace invocations to not see the current window list.

As far as the focus/always-on-top shortcomings, I can see how that would need some built-in solution. In my case, the window I'm trying to move has that behavior anyway so it's not a problem for me.
