### ISSUE TITLE
Default workspace to open new windows

### ISSUE THREAD

**Issue by gabimoncha** [nikitabobko/AeroSpace#216]
I've read through the docs and config file and couldn't find (or maybe missed) where to set the default Workspace / Monitor for new apps and windows.
Is this feature implemented, and if not, is it feasible?

**Comment by nikitabobko** [comment]
If you want all new windows to open up on a specific workspace you can do this:
```toml
[[on-window-detected]]
check-further-callbacks = true
run = 'move-node-to-workspace default_workspace'
```
