### ISSUE TITLE
Ability to ignore something?

### ISSUE THREAD

**Issue by megasuperlexa** [nikitabobko/AeroSpace#220]
I am struggling with the ability to ignore some windows, like for example Quake-style window for iterm2.
It meant to be shown on top of other windows on a hotkey, but currently Aerospace tries to manage it as well.

**Comment by coldenate** [comment]
You can use this to "ignore" certain apps
```toml
[[on-window-detected]]
if.app-id = 'com.apple.finder'
check-further-callbacks = true
run = 'layout floating'
```
