### ISSUE TITLE
AeroSpace moves CleanShot X's supplementary UI elements to primary monitor

### ISSUE THREAD

**Issue by coldenate** [nikitabobko/AeroSpace#221]
Hi @nikitabobko! This app is amazing! I'd like to ask for insight on this bug 

[CleanShot 2024-05-08 at 21 34 08@2x (click me)](https://share.cleanshot.com/jLPrPX8G)

I experience an issue on CleanShot X where their UI for selecting a monitor is captured and grabbed by AeroSpace and moved to the current focused monitor. 
Here's what I think is happening:
The supplementary "Drag to select capture area." button is placed on my secondary display. CleanShot X can notify me that I can optionally use my secondary display. Aerospace recognizes this and moves the button to my primary display, as I just saw it open.

I initially thought this config ↓ would help me, but it does not seem to work for that floating window from the CleanShot UI. 
```toml
[[on-window-detected]]
if.app-id = 'pl.maketheweb.cleanshotx'
check-further-callbacks = true
run = 'layout floating'
```

Do you know how to better select this?
