### ISSUE TITLE
Workspace 10 when using external monitor

### ISSUE THREAD

**Issue by megasuperlexa** [nikitabobko/AeroSpace#222]
Sometimes when I plug in my external monitor, workspace 10 appears. I did not configure it, so it is inaccessible via shortcuts.
<img width="320" alt="image" src="https://github.com/nikitabobko/AeroSpace/assets/24682302/70d1b50f-a12b-489e-8066-1787d851d8b2">

my config:
```toml
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1 --auto-back-and-forth'
alt-2 = 'workspace 2 --auto-back-and-forth'
alt-3 = 'workspace 3 --auto-back-and-forth'
alt-4 = 'workspace 4 --auto-back-and-forth'
alt-5 = 'workspace 5 --auto-back-and-forth'
alt-6 = 'workspace 6 --auto-back-and-forth'
alt-7 = 'workspace 7 --auto-back-and-forth'
alt-8 = 'workspace 8 --auto-back-and-forth'
alt-9 = 'workspace 9 --auto-back-and-forth'
alt-0 = 'workspace 0 --auto-back-and-forth'
ctrl-alt-right = 'workspace next --wrap-around'
ctrl-alt-left = 'workspace prev --wrap-around'
```
