### ISSUE TITLE
Support "AXIdentifier" filter windows in `on-window-detected` callback

### ISSUE THREAD

**Issue by Endy3032** [nikitabobko/AeroSpace#250]
The Arc Browser has a feature called "Little Arc", essentially a temporary "popup" window that is not meant to be tiled

Filtering by app/window name to check whether the window should tile or float is not enough since the popup window's title doesn't have anything to differentiate from normal windows, aside from the `AXIdentifier` property being `Optional(littleBrowserWindow-UUID)` instead of the normal window's `Optional(bigBrowserWindow-UUID)`

The only workarounds I've found is to check whether the title starts with "Space" but that would fail if the space name is not renamed to anything other than "Space [number]", and checking if the title starts with "Little" seemingly only works for popups that are opened with the "Contact the Team" option in the browser (which is quite weird).

I've suggested them to mark little arc windows as dialogs but it'd be great to get more filters implemented in the `on-window-detected` callback too (if it's viable ofc)

Edit: `aerospace debug-windows` output

<details>
  <summary>Normal window</summary>
<pre>company.thebrowser.Browser.window.1721 windowId: 1721
company.thebrowser.Browser.window.1721 workspace: 0
company.thebrowser.Browser.window.1721 treeNodeParent: AppBundle.TilingContainer
company.thebrowser.Browser.window.1721 recognizedAsDialog: false
company.thebrowser.Browser.window.1721 AXTitle: Optional(Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace)
company.thebrowser.Browser.window.1721 AXRole: Optional(AXWindow)
company.thebrowser.Browser.window.1721 AXSubrole: Optional(AXStandardWindow)
company.thebrowser.Browser.window.1721 AXIdentifier: Optional(bigBrowserWindow-A8539292-8A2E-4DE6-8758-12A6A9603F77)
company.thebrowser.Browser.window.1721 AXFocused: Optional(0)
company.thebrowser.Browser.window.1721 AXFullScreen: Optional(0)
company.thebrowser.Browser.window.1721 AXFrame: Optional(<AXValue 0x600000d1e0c0> {value = x:55.000000 y:5.000000 w:1810.000000 h:1069.000000 type = kAXValueCGRectType})
company.thebrowser.Browser.window.1721 AXPosition: Optional(<AXValue 0x6000016778d0> {value = x:55.000000 y:5.000000 type = kAXValueCGPointType})
company.thebrowser.Browser.window.1721 AXGrowArea: nil
company.thebrowser.Browser.window.1721 AXMinimizeButton: AXUIElement {
company.thebrowser.Browser.window.1721      AXRole: Optional(AXButton)
company.thebrowser.Browser.window.1721      AXTitle: nil
company.thebrowser.Browser.window.1721      AXSubrole: Optional(AXMinimizeButton)
company.thebrowser.Browser.window.1721      AXEnabled: Optional(1)
company.thebrowser.Browser.window.1721      AXParent: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      AXTopLevelUIElement: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      AXWindow: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      Ignored: AXFrame, AXSize, AXFocused, AXHelp, AXPosition, AXRoleDescription
company.thebrowser.Browser.window.1721 }
company.thebrowser.Browser.window.1721 AXDocument: nil
company.thebrowser.Browser.window.1721 AXSections: [
company.thebrowser.Browser.window.1721         Optional({
company.thebrowser.Browser.window.1721             SectionDescription = Content;
company.thebrowser.Browser.window.1721             SectionObject = "<AXUIElement 0x600001676160> {pid=39552}";
company.thebrowser.Browser.window.1721             SectionUniqueID = AXContent;
company.thebrowser.Browser.window.1721         }),
company.thebrowser.Browser.window.1721         Optional({
company.thebrowser.Browser.window.1721             SectionDescription = "Top Level Navigator";
company.thebrowser.Browser.window.1721             SectionObject = "<AXUIElement 0x600001676ee0> {pid=39552}";
company.thebrowser.Browser.window.1721             SectionUniqueID = AXTopLevelNavigator;
company.thebrowser.Browser.window.1721         }),
company.thebrowser.Browser.window.1721         Optional({
company.thebrowser.Browser.window.1721             SectionObject = "<AXUIElement 0x600001674210> {pid=39552}";
company.thebrowser.Browser.window.1721             SectionUniqueID = AXContainer;
company.thebrowser.Browser.window.1721         }),
company.thebrowser.Browser.window.1721         Optional({
company.thebrowser.Browser.window.1721             SectionDescription = "Content Navigator";
company.thebrowser.Browser.window.1721             SectionObject = "<AXUIElement 0x600001648210> {pid=39552}";
company.thebrowser.Browser.window.1721             SectionUniqueID = AXContentNavigator;
company.thebrowser.Browser.window.1721         })
company.thebrowser.Browser.window.1721 ]
company.thebrowser.Browser.window.1721 AXCloseButton: AXUIElement {
company.thebrowser.Browser.window.1721      AXRole: Optional(AXButton)
company.thebrowser.Browser.window.1721      AXTitle: nil
company.thebrowser.Browser.window.1721      AXSubrole: Optional(AXCloseButton)
company.thebrowser.Browser.window.1721      AXEnabled: Optional(1)
company.thebrowser.Browser.window.1721      AXParent: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      AXTopLevelUIElement: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      AXWindow: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      Ignored: AXFrame, AXSize, AXFocused, AXHelp, AXPosition, AXRoleDescription, AXEdited
company.thebrowser.Browser.window.1721 }
company.thebrowser.Browser.window.1721 AXMain: Optional(1)
company.thebrowser.Browser.window.1721 AXActivationPoint: Optional(<AXValue 0x60000167f030> {value = x:65.000000 y:19.000000 type = kAXValueCGPointType})
company.thebrowser.Browser.window.1721 AXFullScreenButton: AXUIElement {
company.thebrowser.Browser.window.1721      AXRole: Optional(AXButton)
company.thebrowser.Browser.window.1721      AXTitle: nil
company.thebrowser.Browser.window.1721      AXSubrole: Optional(AXFullScreenButton)
company.thebrowser.Browser.window.1721      AXEnabled: Optional(1)
company.thebrowser.Browser.window.1721      AXParent: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      AXTopLevelUIElement: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      AXWindow: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      Ignored: AXFrame, AXSize, AXFocused, AXChildren, AXHelp, AXPosition, AXRoleDescription
company.thebrowser.Browser.window.1721 }
company.thebrowser.Browser.window.1721 AXProxy: nil
company.thebrowser.Browser.window.1721 AXDefaultButton: nil
company.thebrowser.Browser.window.1721 AXMinimized: Optional(0)
company.thebrowser.Browser.window.1721 AXParent: Optional(<AXUIElement Application 0x60000167f030> {pid=39552})
company.thebrowser.Browser.window.1721 AXTitleUIElement: nil
company.thebrowser.Browser.window.1721 AXCancelButton: nil
company.thebrowser.Browser.window.1721 AXModal: Optional(0)
company.thebrowser.Browser.window.1721 AXZoomButton: AXUIElement {
company.thebrowser.Browser.window.1721      AXRole: Optional(AXButton)
company.thebrowser.Browser.window.1721      AXTitle: nil
company.thebrowser.Browser.window.1721      AXSubrole: Optional(AXFullScreenButton)
company.thebrowser.Browser.window.1721      AXEnabled: Optional(1)
company.thebrowser.Browser.window.1721      AXParent: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      AXTopLevelUIElement: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      AXWindow: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1721      Ignored: AXFrame, AXSize, AXFocused, AXChildren, AXHelp, AXPosition, AXRoleDescription
company.thebrowser.Browser.window.1721 }
company.thebrowser.Browser.window.1721 AXSize: Optional(<AXValue 0x600001662ca0> {value = w:1810.000000 h:1069.000000 type = kAXValueCGSizeType})
company.thebrowser.Browser.window.1721 AXToolbarButton: nil
company.thebrowser.Browser.window.1721 Ignored: AXChildrenInNavigationOrder, AXChildren, AXRoleDescription
company.thebrowser.Browser             AXRole: Optional(AXApplication)
company.thebrowser.Browser             AXTitle: Optional(Arc)
company.thebrowser.Browser             AXFunctionRowTopLevelElements: [
company.thebrowser.Browser             ]
company.thebrowser.Browser             AXFrame: nil
company.thebrowser.Browser             AXFocusedUIElement: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWebArea", subrole=nil)
company.thebrowser.Browser             AXFrontmost: Optional(1)
company.thebrowser.Browser             AXExtrasMenuBar: nil
company.thebrowser.Browser             AXMainWindow: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser             AXFocusedWindow: AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser             AXMenuBar: Optional(<AXUIElement 0x600001648210> {pid=39552})
company.thebrowser.Browser             AXWindows: [
company.thebrowser.Browser                 AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow"),
company.thebrowser.Browser                 AXUIElement(windowId=1853, title="awd - Brave Search", role="AXWindow", subrole="AXStandardWindow"),
company.thebrowser.Browser                 AXUIElement(windowId=290, title="AeroSpace Commands", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser             ]
company.thebrowser.Browser             AXSize: nil
company.thebrowser.Browser             AXPosition: nil
company.thebrowser.Browser             Ignored: AXChildren, AXChildrenInNavigationOrder, AXEnhancedUserInterface, AXPreferredLanguage, AXRoleDescription, AXHidden</pre>
</details>

<details>
  <summary>Little Arc</summary>
  <pre>
company.thebrowser.Browser.window.1989 windowId: 1989
company.thebrowser.Browser.window.1989 workspace: 0
company.thebrowser.Browser.window.1989 treeNodeParent: AppBundle.TilingContainer
company.thebrowser.Browser.window.1989 recognizedAsDialog: false
company.thebrowser.Browser.window.1989 AXTitle: Optional(Space 1)
company.thebrowser.Browser.window.1989 AXRole: Optional(AXWindow)
company.thebrowser.Browser.window.1989 AXSubrole: Optional(AXStandardWindow)
company.thebrowser.Browser.window.1989 AXIdentifier: Optional(littleBrowserWindow-9779869B-69A1-4FF6-8765-34B748C226B6)
company.thebrowser.Browser.window.1989 AXFocused: Optional(0)
company.thebrowser.Browser.window.1989 AXFullScreen: Optional(0)
company.thebrowser.Browser.window.1989 AXFrame: Optional(<AXValue 0x600000d12b00> {value = x:1410.000000 y:20.000000 w:490.000000 h:329.000000 type = kAXValueCGRectType})
company.thebrowser.Browser.window.1989 AXPosition: Optional(<AXValue 0x6000016406c0> {value = x:1410.000000 y:20.000000 type = kAXValueCGPointType})
company.thebrowser.Browser.window.1989 AXGrowArea: nil
company.thebrowser.Browser.window.1989 AXMinimizeButton: AXUIElement {
company.thebrowser.Browser.window.1989      AXRole: Optional(AXButton)
company.thebrowser.Browser.window.1989      AXTitle: nil
company.thebrowser.Browser.window.1989      AXSubrole: Optional(AXMinimizeButton)
company.thebrowser.Browser.window.1989      AXEnabled: Optional(1)
company.thebrowser.Browser.window.1989      AXParent: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      AXTopLevelUIElement: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      AXWindow: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      Ignored: AXFrame, AXSize, AXFocused, AXHelp, AXPosition, AXRoleDescription
company.thebrowser.Browser.window.1989 }
company.thebrowser.Browser.window.1989 AXDocument: nil
company.thebrowser.Browser.window.1989 AXSections: [
company.thebrowser.Browser.window.1989         Optional({
company.thebrowser.Browser.window.1989             SectionDescription = Content;
company.thebrowser.Browser.window.1989             SectionObject = "<AXUIElement 0x60000167af10> {pid=39552}";
company.thebrowser.Browser.window.1989             SectionUniqueID = AXContent;
company.thebrowser.Browser.window.1989         }),
company.thebrowser.Browser.window.1989         Optional({
company.thebrowser.Browser.window.1989             SectionObject = "<AXUIElement 0x60000167bde0> {pid=39552}";
company.thebrowser.Browser.window.1989             SectionUniqueID = AXContainer;
company.thebrowser.Browser.window.1989         }),
company.thebrowser.Browser.window.1989         Optional({
company.thebrowser.Browser.window.1989             SectionDescription = "Content Navigator";
company.thebrowser.Browser.window.1989             SectionObject = "<AXUIElement 0x60000167a5b0> {pid=39552}";
company.thebrowser.Browser.window.1989             SectionUniqueID = AXContentNavigator;
company.thebrowser.Browser.window.1989         })
company.thebrowser.Browser.window.1989 ]
company.thebrowser.Browser.window.1989 AXCloseButton: AXUIElement {
company.thebrowser.Browser.window.1989      AXRole: Optional(AXButton)
company.thebrowser.Browser.window.1989      AXTitle: nil
company.thebrowser.Browser.window.1989      AXSubrole: Optional(AXCloseButton)
company.thebrowser.Browser.window.1989      AXEnabled: Optional(1)
company.thebrowser.Browser.window.1989      AXParent: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      AXTopLevelUIElement: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      AXWindow: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      Ignored: AXFrame, AXSize, AXFocused, AXHelp, AXPosition, AXRoleDescription, AXEdited
company.thebrowser.Browser.window.1989 }
company.thebrowser.Browser.window.1989 AXMain: Optional(1)
company.thebrowser.Browser.window.1989 AXActivationPoint: Optional(<AXValue 0x6000016660a0> {value = x:1420.000000 y:34.000000 type = kAXValueCGPointType})
company.thebrowser.Browser.window.1989 AXFullScreenButton: AXUIElement {
company.thebrowser.Browser.window.1989      AXRole: Optional(AXButton)
company.thebrowser.Browser.window.1989      AXTitle: nil
company.thebrowser.Browser.window.1989      AXSubrole: Optional(AXFullScreenButton)
company.thebrowser.Browser.window.1989      AXEnabled: Optional(1)
company.thebrowser.Browser.window.1989      AXParent: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      AXTopLevelUIElement: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      AXWindow: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      Ignored: AXFrame, AXSize, AXFocused, AXChildren, AXHelp, AXPosition, AXRoleDescription
company.thebrowser.Browser.window.1989 }
company.thebrowser.Browser.window.1989 AXProxy: nil
company.thebrowser.Browser.window.1989 AXDefaultButton: nil
company.thebrowser.Browser.window.1989 AXMinimized: Optional(0)
company.thebrowser.Browser.window.1989 AXParent: Optional(<AXUIElement Application 0x600001663060> {pid=39552})
company.thebrowser.Browser.window.1989 AXTitleUIElement: nil
company.thebrowser.Browser.window.1989 AXCancelButton: nil
company.thebrowser.Browser.window.1989 AXModal: Optional(0)
company.thebrowser.Browser.window.1989 AXZoomButton: AXUIElement {
company.thebrowser.Browser.window.1989      AXRole: Optional(AXButton)
company.thebrowser.Browser.window.1989      AXTitle: nil
company.thebrowser.Browser.window.1989      AXSubrole: Optional(AXFullScreenButton)
company.thebrowser.Browser.window.1989      AXEnabled: Optional(1)
company.thebrowser.Browser.window.1989      AXParent: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      AXTopLevelUIElement: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      AXWindow: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser.window.1989      Ignored: AXFrame, AXSize, AXFocused, AXChildren, AXHelp, AXPosition, AXRoleDescription
company.thebrowser.Browser.window.1989 }
company.thebrowser.Browser.window.1989 AXSize: Optional(<AXValue 0x600001678600> {value = w:490.000000 h:329.000000 type = kAXValueCGSizeType})
company.thebrowser.Browser.window.1989 AXToolbarButton: nil
company.thebrowser.Browser.window.1989 Ignored: AXChildrenInNavigationOrder, AXChildren, AXRoleDescription
company.thebrowser.Browser             AXRole: Optional(AXApplication)
company.thebrowser.Browser             AXTitle: Optional(Arc)
company.thebrowser.Browser             AXFunctionRowTopLevelElements: [
company.thebrowser.Browser             ]
company.thebrowser.Browser             AXFrame: nil
company.thebrowser.Browser             AXFocusedUIElement: AXUIElement(windowId=1989, title=nil, role="AXTextField", subrole=nil)
company.thebrowser.Browser             AXFrontmost: Optional(1)
company.thebrowser.Browser             AXExtrasMenuBar: nil
company.thebrowser.Browser             AXMainWindow: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser             AXFocusedWindow: AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser             AXMenuBar: Optional(<AXUIElement 0x600001663060> {pid=39552})
company.thebrowser.Browser             AXWindows: [
company.thebrowser.Browser                 AXUIElement(windowId=1989, title="Space 1", role="AXWindow", subrole="AXStandardWindow"),
company.thebrowser.Browser                 AXUIElement(windowId=1721, title="Support for other ways to filter windows in `on-window-detected` callback · Issue #250 · nikitabobko/AeroSpace", role="AXWindow", subrole="AXStandardWindow"),
company.thebrowser.Browser                 AXUIElement(windowId=1853, title="awd - Brave Search", role="AXWindow", subrole="AXStandardWindow"),
company.thebrowser.Browser                 AXUIElement(windowId=290, title="AeroSpace Commands", role="AXWindow", subrole="AXStandardWindow")
company.thebrowser.Browser             ]
company.thebrowser.Browser             AXSize: nil
company.thebrowser.Browser             AXPosition: nil
company.thebrowser.Browser             Ignored: AXChildren, AXChildrenInNavigationOrder, AXEnhancedUserInterface, AXPreferredLanguage, AXRoleDescription, AXHidden
</pre>
</summary>

**Comment by abitbetterthanyesterday** [comment]
Have you found a workaround @Endy3032 ?

**Comment by Endy3032** [comment]
> Have you found a workaround @Endy3032 ?
> 
> EDIT: Any chance you could show your config for you workaround? Thank you :)

sorry for the late reply, the workaround i used isn't entirely accurate but i'll send anyway, hope it helps somewhat :D
```toml
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
check-further-callbacks = true
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
if.window-title-regex-substring = '^[^Space|Little]'
check-further-callbacks = true
run = 'layout tiling'
```

**Comment by notjl** [comment]
Is there a way to prevent Little Arc from going to the dedicated workspace I set for Arc? I want it to open up in the workspace where I clicked the link in (for example, Discord links [Discord is set to workspace 3]).

Here's my configuration for Arc currently.
```toml
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
check-further-callbacks = true
run = 'move-node-to-workspace 2'
```

**Comment by xkraty** [comment]
> > Have you found a workaround @Endy3032 ?
> > EDIT: Any chance you could show your config for you workaround? Thank you :)
> 
> sorry for the late reply, the workaround i used isn't entirely accurate but i'll send anyway, hope it helps somewhat :D
> 
> ```toml
> [[on-window-detected]]
> if.app-id = 'company.thebrowser.Browser'
> check-further-callbacks = true
> run = 'layout floating'
> 
> [[on-window-detected]]
> if.app-id = 'company.thebrowser.Browser'
> if.window-title-regex-substring = '^[^Space|Little]'
> check-further-callbacks = true
> run = 'layout tiling'
> ```

Hey there, I'm an Arc user as well and thanks for your workaround, however, my Little Arc doesn't seem to have `Little` in the title

**Comment by dev-msp** [comment]
Hey, I made a change to the regular expression - `[^...]` is for negative matches on individual characters. Frankly I don't see how this would ever have worked!

You might have been thinking of `(^Space|Little)`, but that wouldn't quite do it either, because the `^` character only signifies negation when it's the first character inside `[]`. So `(^Space|Little)` would be a positive match on `Space` at the start of the line OR a match on `Little` anywhere in the string. 

Luckily, Swift regular expressions include support for [negative lookahead assertions](https://github.com/swiftlang/swift-experimental-string-processing/blob/39cb22d96d90ee7cb308b1153e106e50598afdd9/Documentation/Evolution/RegexSyntaxRunTimeConstruction.md#lookahead-and-lookbehind). The snippet below works like a charm for me.

(Also I removed `Little` from the pattern since I don't see that in my window titles either.)

```
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
check-further-callbacks = true
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
if.window-title-regex-substring = '^(?!Space)'
check-further-callbacks = true
run = 'layout tiling'
```

**Comment by xkraty** [comment]
@dev-msp Thanks for your answer, feeling quite a noob about that but I guess I'm missing something? Here is my config:

```toml
# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    #  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = 'move-mouse window-lazy-center'
# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       15
outer.bottom =     15
outer.top =        15
outer.right =      15

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace Space1'
alt-2 = 'workspace Space2'
alt-3 = 'workspace Space3'
alt-4 = 'workspace Space4'
alt-5 = 'workspace Space5'
alt-6 = 'workspace Space6'
alt-7 = 'workspace Space7'
alt-8 = 'workspace Space8'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = ['move-node-to-workspace 1', 'workspace Space1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace Space2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace Space3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace Space4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace Space5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace Space6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace Space7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace Space8']

# Custom Kraty's Commands
alt-shift-f = 'fullscreen'
cmd-h = []
cmd-alt-h = []

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layouti
backspace = ['close-all-windows-but-current', 'mode main']
alt-r = 'mode resize'

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[mode.resize.binding]      # 2. Declare 'resize' binding mode
minus = 'resize smart -50'
equal = 'resize smart +50'

[workspace-to-monitor-force-assignment]
Space1 = ['secondary', 'main']
Space2 = ['secondary', 'main']
Space3 = ['secondary', 'main']
Space4 = ['secondary', 'main']

# Little Arc
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
check-further-callbacks = true
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
if.window-title-regex-substring = '^(?!Space)'
check-further-callbacks = true
run = 'layout tiling'

# Automove

[[on-window-detected]]
if.app-id = 'com.jetbrains.rubymine'
check-further-callbacks = true
run = ['move-node-to-workspace Space2']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
check-further-callbacks = true
run = ['move-node-to-workspace Space1']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
check-further-callbacks = true
run = ['move-node-to-workspace 8']

# Floating

[[on-window-detected]]
if.app-id = 'com.apple.finder'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
check-further-callbacks = true
run = ['layout floating']
```

Thanks
Chris
