### ISSUE TITLE
Feature: `workspace next|prev --all`

### ISSUE THREAD

**Issue by jilyaluk** [nikitabobko/AeroSpace#264]
Hi! First of all, kudos for creating such awesome tool! I tried to use yabai in the past, but couldn't bear native worspace switching speed (even with reduced animations), compared to i3. AeroSpace's virtual workspaces work extremely fast in comparison.

### Use-case

I'd like to bind alt-tab/alt-shift-tab to cycle through all workspaces, regardless of monitor. This can be solved like that:
```toml
alt-tab = 'exec-and-forget aerospace list-workspaces --all | aerospace workspace --wrap-around next'
alt-shift-tab = 'exec-and-forget aerospace list-workspaces --all | aerospace workspace --wrap-around prev'
```

However, this adds significant delay: ~30-50ms for listing workspaces, and 50+ ms for spawning bash and piping/calling `aerospace workspace`.

Having static list of workspaces, `aerospace list-workspaces --all` can be replaced with `seq 1 9` or even static `echo $'1\n2\n...'`, however this does not eliminate overhead of spawning subprocesses and calling `aerospace` CLI, which becomes noticeable, because I navigate workspaces in that way quite a lot.

### Proposal

Argument `--all`  could be added to `workspace (next|prev)` syntax to implement this kind of behaviour (similar to `list-(windows|workspaces)`)

I'd be happy to submit a PR if you're okay with such feature.
