### ISSUE TITLE
Error hide  window of crossover application

### ISSUE THREAD

**Issue by shininome** [nikitabobko/AeroSpace#279]
When I use crossover to play Windows games, sometimes Aerospace hide the game window to the bottom right corner of the screen. 

I have to change the screen resolution to locate the hidden window, but I cannot consistently trigger this bug; most of the time it behaves normally.

```toml
[[on-window-detected]]
if.app-id = 'com.codeweavers.CrossOver'
run = ['layout floating','move-node-to-workspace 5']


[[on-window-detected]]
if.window-title-regex-substring = 'exe$'
run = 'layout floating'
```

```
72456 | com.codeweavers.CrossOver    | CrossOver
72492 | NULL-APP-ID                  | Sakura.exe
```
