### ISSUE TITLE
Assign applications to open in workspace

### ISSUE THREAD

**Issue by ostenning** [nikitabobko/AeroSpace#302]
Is it possible to open certain apps automatically in a designated workspace? For example, I want firefox always to open in workspace 1, whilst I want my IDE in workspace 2 etc. 
At the moment, I open these apps and have to always resort them into their respective workspaces which is tiresome.

**Comment by bcremer** [comment]
This can be implemented using the `on-window-detected`-callbacks.

See: https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback

```toml
[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
if.window-title-regex-substring = 'Picture-in-Picture'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.jetbrains.PhpStorm'
run = 'move-node-to-workspace 2'
```
