### ISSUE TITLE
Exit binding mode by pressing a non-defined key in that mode

### ISSUE THREAD

**Issue by mfiers** [nikitabobko/AeroSpace#354]
It would be helpful if there was the (configurable?) option to exit a binding mode when pressing any key that is not defined in that mode. 

I've had a few cases where I got stuck in the (service) binding mode when misspressing a key, after which I'm mentally back in the main binding, but aerospace is waiting for a service command.

**Comment by thewinger** [comment]
+1 for this.
It also happens to me that I'm in, for example, move.binding, forget that I'm there, start writing and all windows move around :/

**Comment by theherk** [comment]
This is a good idea. You could sort of brute for it, with something like:

```toml
[mode.launch.binding]
    # ... your actual bindings ...
    # everything else back to main
    a = 'mode main'
    b = 'mode main'
    c = 'mode main'
    # ... etc
```

but that leaves a maintenance burden of not only creating each for each mode, but also removing each when you add a new binding. I think having keys not in a mode leave the mode would be a great improvement. An additional feature that would help address this would be a mode timeout attribute so it leaves on its own if not receiving a configured key in some time. That also could probably be done now with a mode callback exec and forget, but a simple property would be clean.
