### ISSUE TITLE
How do I set the gap for a specific mode?

### ISSUE THREAD

**Issue by samholmes** [nikitabobko/AeroSpace#369]
I'm a modal junkie, so I like my modal experiences. This mean's I prefer to have a single key-binding to change from main mode to an alt mode. In the alt mode I will have all my bindings for my commands as well as a binding to exit back to main. This minimizes chording in my keybindings.

However, I like modal experiences where I can show a clear indicator to whether I am in a particular mode. This visual indicator aids in communicating to the user what mode is currently activated. I figured the gap config would be perfect for this: I'd have gaps set to 0 in main mode, and 10 in my alt mode.

How do I configure the toml file such that the gap is set but only for a specific mode?

**Comment by nikitabobko** [comment]
Please keep and eye on #278 and #377. Once these two are implemented, the following will become possible:
```toml
[gaps]
outer.top = '''
if test "$(list-modes --active)" == main do
    echo 10
elif test "$(list-modes --active)" == service do
    echo 0
end
'''
```

**Comment by nikitabobko** [comment]
Alternatively if #355 gets fixed
```toml
[mode.main.binding]
alt-shift-semicolon = ['mode service', 'config --set gaps.outer.top 0']

[mode.service.binding]
esc = ['mode main', 'config --set gaps.outer.top 10']
```

---

```toml
[gaps]
outer.top = 'echo $GAPS || echo 0'

[mode.main.binding]
alt-shift-semicolon = ['mode service', 'set-env GAPS 0']

[mode.service.binding]
esc = ['mode main', 'set-env GAPS 10']
```
