### ISSUE TITLE
Mouse Events

### ISSUE THREAD

**Issue by samholmes** [nikitabobko/AeroSpace#371]
Events like mouse move or mouse click would be useful to exit modes. My current main mode only has one binding to enter an alt mode with all my single key bindings to navigate windows etc. The space bar is the exit binding from this alt mode. Being able to setup mouse events to also exit this alt mode would be very handy and useful to not accidentally forget that I'm in the alt mode.

**Comment by nikitabobko** [comment]
Something like this could be supported in future versions

```toml
[mode.service.binding]
  leftMouseUp = 'mode main'
  leftMouseDown = 'mode main'
  rightMouseUp = 'mode main'
  rightMouseDown = 'mode main'
```

Things to consider: feature interaction with modifiers

```toml
[mode.main.binding]
  alt-leftMouseDown = 'grab-window on'
  leftMouseUp = 'grab-window off'
```

Hypothetical synopsis:

```
grab-window on --resize
grab-window on --swap [--join-with-modifier=<modifier>]
grab-window on --join-with [--swap-modifier=<modifier>]
grab-window off
```
