### ISSUE TITLE
Disable wrap in "focus" command.

### ISSUE THREAD

**Issue by samholmes** [nikitabobko/AeroSpace#372]
Right now the move command will wrap to the begging of a set of nodes if the currently focused node is the last node:

For example, say I have three windows horizontally tiled like so:

| _ | _ | x |

The x denotes the focused window. If I focus to the right then the left-most window will be focused:

| x | _ | _ |

This wrap behavior is a little confusing when shuffling windows. I'd much rather the focus right do nothing as if it reach the end of the set of windows. This way I can quickly move to the beginning or end of some accordion or tile layout.

A config to disable this sort of wrapping behavior would be really useful for my setup.

**Comment by nikitabobko** [comment]
```
aerospace focus --boundaries-actions stop
```

**Comment by samholmes** [comment]
> ```
> aerospace focus --boundaries-actions stop
> ```

<img width="420" alt="Screenshot 2024-08-12 at 2 24 34 PM" src="https://github.com/user-attachments/assets/62114af3-ae90-4518-996b-ec076374c628">

I receive this error message when loading my config with the suggested changes:

```toml
h = ['focus --boundaries-actions stop left', 'move-mouse window-force-center']
j = ['focus --boundaries-actions stop down', 'move-mouse window-force-center']
k = ['focus --boundaries-actions stop up', 'move-mouse window-force-center']
l = ['focus --boundaries-actions stop right', 'move-mouse window-force-center']
```
