### ISSUE TITLE
`move-node-to-workspace` not triggering `exec-on-workspace-change` in `[[on-window-detected]]` clause

### ISSUE THREAD

**Issue by typkrft** [nikitabobko/AeroSpace#402]
An established event for `sketchybar` appears not trigger when window is automatically moved to a workspace. 

Relevant toml
```toml
# Sketchybar
exec-on-workspace-change = [
    '/bin/bash', 
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = ['move-node-to-workspace 3']
```

Relevant sketchybarrc
```bash
sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change space_windows_change space_change \
        --set space.$sid \
        background.color=0xffffffff  \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        icon.drawing=off \
        label="$sid" \
        label.padding_right=6 \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_DIR/aerospace.sh $sid"
done
```

Aerospace Script
```bash
#!/usr/bin/env bash

# Set Background
if [[ -z "$FOCUSED_WORKSPACE" ]]; then
    focused_space=$(aerospace list-workspaces --focused)
    sketchybar --set space.$focused_space background.drawing=on label.color=0xff000000 label="$focused_space [$(aerospace list-windows --workspace focused | wc -l | grep -Eo '\d')]"
elif [[ "$1" = "$FOCUSED_WORKSPACE" ]]; then
    sketchybar --set $NAME background.drawing=on label.color=0xff000000 label="$1 [$(aerospace list-windows --workspace focused | wc -l | grep -Eo '\d')]"
else
    sketchybar --set $NAME background.drawing=off label.color=0x44ffffff label="$(echo $NAME | grep -Eo '[0-9]{1,4}')"
fi
```
