### ISSUE TITLE
Feature request: Array for `on-window-detected` app ids

### ISSUE THREAD

**Issue by frankfriberg** [nikitabobko/AeroSpace#460]
First of all, love this app! 🫶 

With `yabai` as I used before this, I manually handled what was handled, but `aerospace` has a better way of automatically handling so I don't have to add as much config.
But I have to repeat `on-window-detected` config to make certain apps float as I don't need these fullscreen.

My request is for the `if.app-id` to be able to get an array and it will do the run for all those app-ids like this:
```toml
[[on-window-detected]]
if.app-id = ["com.1password.1password", "ru.keepcoder.Telegram", "com.apple.iCal"]
```
instead of:
```toml
[[on-window-detected]]
if.app-id = "com.1password.1password"
run = "layout floating"

[[on-window-detected]]
if.app-id = "ru.keepcoder.Telegram"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.apple.iCal"
run = "layout floating"
```

ℹ️ I have not thought about any scenario that this might break when running for multiple apps, I only use this for floating the apps 😄 

## Checklist
- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - array
- [x] I've read the documentation
- [x] I've searched in the documentation. My search queries were:
 - array

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```
