### ISSUE TITLE
Aerospace not detecting Zathura PDF viewer (NULL-APP-BUNDLE-ID)

### ISSUE THREAD

**Issue by SylvanFranklin** [nikitabobko/AeroSpace#486]
I have the following in my config:
```toml
[[on-window-detected]]
if.app-id = 'NULL-APP-BUNDLE-ID'
if.app-name-regex-substring = 'zathura'
if.window-title-regex-substring = 'zathura'
run = 'move-node-to-workspace P'
```
Zathura does not move to space P. It does appear in the dock, application switcher, and is hidden when I run `aerospace list-apps macos-native-hidden`
