### ISSUE TITLE
Not able to force workspace to a specific monitor

### ISSUE THREAD

**Issue by wwvuillemot** [nikitabobko/AeroSpace#519]
**YOUR TEXT**

I'm trying to update `~/aerospace.toml` with the following

```toml
# Set monitors. See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
10 = '^built-in retina display$'
```

I've tried variations of this

```toml
[[workspace-to-monitor-force-assignment]]
10 = '^built-in retina display$'
```

```toml
# Set monitors. See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
'10' = '^built-in retina display$'
```

```toml
# Set monitors. See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
10 = 'Built-in Retina Display'
```

But I get this error, or a variation there of:

![スクリーンショット 2024-09-18 9 29 01](https://github.com/user-attachments/assets/252d0867-1f35-470c-9ae0-9628f5b85dd4)

## Rationale 

I want to ensure that my app mappings such as 

```toml
[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = "move-node-to-workspace 10"
```

Always reliably go to the native window when using another monitor as my main monitor.  I'm finding that Aerospace does not reliably set the laptop monitor to `10`

## Checklist

- [X] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - [GitHub Repo](https://github.com/search?q=repo%3Anikitabobko%2FAeroSpace%20workspace-to-monitor-force-assignment&type=code)
    - Was attempting to parse the code in hopes I might see how my 
  - [Google](https://www.google.com/search?q=%22%5Bworkspace-to-monitor-force-assignment%5D%22+%22workspace-to-monitor-force-assignment.key-mapping%3A+Expected+types+are+%27string%27+or+%27integer%27.+But+actual+type+is+%27table%27%22&client=safari&sca_esv=5a44afa316a78899&sca_upv=1&rls=en&ei=Yv_qZt_mEdmZ0PEPtOfgqAw&ved=0ahUKEwjfn-a69MyIAxXZDDQIHbQzGMUQ4dUDCA8&uact=5&oq=%22%5Bworkspace-to-monitor-force-assignment%5D%22+%22workspace-to-monitor-force-assignment.key-mapping%3A+Expected+types+are+%27string%27+or+%27integer%27.+But+actual+type+is+%27table%27%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiowEiW3dvcmtzcGFjZS10by1tb25pdG9yLWZvcmNlLWFzc2lnbm1lbnRdIiAid29ya3NwYWNlLXRvLW1vbml0b3ItZm9yY2UtYXNzaWdubWVudC5rZXktbWFwcGluZzogRXhwZWN0ZWQgdHlwZXMgYXJlICdzdHJpbmcnIG9yICdpbnRlZ2VyJy4gQnV0IGFjdHVhbCB0eXBlIGlzICd0YWJsZSciMggQABiiBBiJBTIIEAAYgAQYogQyCBAAGIAEGKIEMggQABiiBBiJBUimElCDB1jQD3ABeAGQAQCYAW-gAaYBqgEDMS4xuAEDyAEA-AEB-AECmAIDoAK2AcICChAAGLADGNYEGEeYAwCIBgGQBgiSBwMyLjGgB-kF&sclient=gws-wiz-serp)
    - Other variations of goo
- [X] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [X] I've searched in the documentation. My search queries were:
  - https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
Please post your whole snippet. Judging by the error message, I think you wrote something like this:

```toml
[workspace-to-monitor-force-assignment]
[key-mapping]
10 = 'Built-in Retina Display'
```

**Comment by wwvuillemot** [comment]
Included the entirety of the configuration.  Scroll to `### CONFIGURATION IN QUESTION` 

```toml
# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

### CONFIGURATION IN QUESTION
# Set monitors. See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
#[workspace-to-monitor-force-assignment]
#10 = '^built-in retina display$'
### CONFIGURATION IN QUESTION

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse monitor-lazy-center"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-d = 'workspace D'
alt-e = 'workspace E'
# alt-f = 'workspace F'
alt-g = 'workspace G'
alt-i = 'workspace I'
alt-m = 'workspace M'
alt-n = 'workspace N'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-q = 'workspace Q'
alt-r = 'workspace R'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-u = 'workspace U'
alt-v = 'workspace V'
alt-w = 'workspace W'
alt-x = 'workspace X'
alt-y = 'workspace Y'
alt-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-a = 'move-node-to-workspace A'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-e = 'move-node-to-workspace E'
# alt-shift-f = 'move-node-to-workspace F'
alt-shift-g = 'move-node-to-workspace G'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-m = 'move-node-to-workspace M'
alt-shift-n = 'move-node-to-workspace N'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-r = 'move-node-to-workspace R'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-v = 'move-node-to-workspace V'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-x = 'move-node-to-workspace X'
alt-shift-y = 'move-node-to-workspace Y'
alt-shift-z = 'move-node-to-workspace Z'

alt-shift-f = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-left = ['join-with left', 'mode main']
alt-shift-down = ['join-with down', 'mode main']
alt-shift-up = ['join-with up', 'mode main']
alt-shift-right = ['join-with right', 'mode main']

# auto-move apps to windows
[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = "move-node-to-workspace 10"

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = "move-node-to-workspace D"

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = "move-node-to-workspace C"


[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = "move-node-to-workspace P"

[[on-window-detected]]
if.app-id = 'com.apple.iphonesimulator'
run = "move-node-to-workspace S"

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'com.github.GitHubClient'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = "move-node-to-workspace Z"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace S"

```

**Comment by wwvuillemot** [comment]
That was a clue

I moved the confirguration to below `qwerty`

```toml
# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Set monitors. See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
10 = '^built-in retina display$'
```

If I swap those two I get the error.

I considered resolved for my needs.  But it might just mean added a comment to the default config to put stuff below the `key-mapping.preset = 'qwerty'` line. 

No idea if that is universally a good idea or required or not.

LOVE THIS TOOL!
