### ISSUE TITLE
Default root container layout isn't applied to the workspace on the main display

### ISSUE THREAD

**Issue by shoplab7** [nikitabobko/AeroSpace#568]
I have
`default-root-container-layout = 'accordion'`
in config, but when I launch aerospace, workspace on the main display uses tiles, while workspaces on external displays use accordion.

<details>
  <summary>Config</summary> 

  ```
  # Place a copy of this config to ~/.aerospace.toml
  # After that, you can edit ~/.aerospace.toml to your liking
  
  # It's not necessary to copy all keys to your config.
  # If the key is missing in your config, "default-config.toml" will serve as a fallback
  
  # You can use it to add commands that run after login to macOS user session.
  # 'start-at-login' needs to be 'true' for 'after-login-command' to work
  # Available commands: https://nikitabobko.github.io/AeroSpace/commands
  after-login-command = []
  
  # You can use it to add commands that run after AeroSpace startup.
  # 'after-startup-command' is run after 'after-login-command'
  # Available commands : https://nikitabobko.github.io/AeroSpace/commands
  after-startup-command = []
  
  # Start AeroSpace at login
  start-at-login = true 
  
  # Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
  enable-normalization-flatten-containers = true
  enable-normalization-opposite-orientation-for-nested-containers = true
  
  # See: https://nikitabobko.github.io/AeroSpace/guide#layouts
  # The 'accordion-padding' specifies the size of accordion padding
  # You can set 0 to disable the padding feature
  accordion-padding = 0
  
  # Possible values: tiles|accordion
  default-root-container-layout = 'accordion'
  
  # Possible values: horizontal|vertical|auto
  # 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
  #               tall monitor (anything higher than wide) gets vertical orientation
  default-root-container-orientation = 'auto'
  
  # Possible values: (qwerty|dvorak)
  # See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
  key-mapping.preset = 'qwerty'
  
  # Mouse follows focus when focused monitor changes
  # Drop it from your config, if you don't like this behavior
  # See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
  # See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
  on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
  on-focus-changed = "move-mouse window-lazy-center"
  
  # Gaps between windows (inner-*) and between monitor edges (outer-*).
  # Possible values:
  # - Constant:     gaps.outer.top = 8
  # - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
  #                 In this example, 24 is a default value when there is no match.
  #                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
  #                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
  [gaps]
  inner.horizontal = 0
  inner.vertical =   0
  outer.left =       0
  outer.bottom =     0
  outer.top =        0
  outer.right =      0
  
  # 'main' binding mode declaration
  # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
  # 'main' binding mode must be always presented
  [mode.main.binding]
  
  # All possible keys:
  # - Letters.        a, b, c, ..., z
  # - Numbers.        0, 1, 2, ..., 9
  # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
  # - F-keys.         f1, f2, ..., f20
  # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
  #                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
  # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
  #                   keypadMinus, keypadMultiply, keypadPlus
  # - Arrows.         left, down, up, right
  
  # All possible modifiers: cmd, alt, ctrl, shift
  
  # All possible commands: https://nikitabobko.github.io/AeroSpace/commands
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
  # You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
  # alt-enter = '''exec-and-forget osascript -e '
  # tell application "Terminal"
  #     do script
  #     activate
  # end tell'
  # '''
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#layout
  alt-slash = 'layout tiles horizontal vertical'
  alt-comma = 'layout accordion horizontal vertical'
  alt-t = 'layout floating tiling'
  
  # Monitor
  cmd-alt-ctrl-shift-n = 'focus-monitor --wrap-around next'
  cmd-alt-ctrl-shift-p = 'focus-monitor --wrap-around prev'
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#focus
  cmd-alt-ctrl-shift-h = 'focus left --ignore-floating'
  cmd-alt-ctrl-shift-j = 'focus down --ignore-floating'
  cmd-alt-ctrl-shift-k = 'focus up --ignore-floating'
  cmd-alt-ctrl-shift-l = 'focus right --ignore-floating'
  
  alt-h = 'focus left'
  alt-j = 'focus down'
  alt-k = 'focus up'
  alt-l = 'focus right'
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#move
  alt-shift-h = 'move left'
  alt-shift-j = 'move down'
  alt-shift-k = 'move up'
  alt-shift-l = 'move right'
  
  alt-n = ['move-node-to-monitor --wrap-around next', 'focus-monitor --wrap-around next']
  alt-p = ['move-node-to-monitor --wrap-around prev', 'focus-monitor --wrap-around prev']
  
  alt-b = 'focus-back-and-forth'
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#resize
  alt-shift-minus = 'resize smart -50'
  alt-shift-equal = 'resize smart +50'
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
  alt-1 = 'workspace 1'
  alt-2 = 'workspace 2'
  alt-3 = 'workspace 3'
  # alt-4 = 'workspace 4'
  # alt-5 = 'workspace 5'
  # alt-6 = 'workspace 6'
  # alt-7 = 'workspace 7'
  # alt-8 = 'workspace 8'
  # alt-9 = 'workspace 9'
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
  alt-shift-1 = 'move-node-to-workspace 1'
  alt-shift-2 = 'move-node-to-workspace 2'
  alt-shift-3 = 'move-node-to-workspace 3'
  # alt-shift-4 = 'move-node-to-workspace 4'
  # alt-shift-5 = 'move-node-to-workspace 5'
  # alt-shift-6 = 'move-node-to-workspace 6'
  # alt-shift-7 = 'move-node-to-workspace 7'
  # alt-shift-8 = 'move-node-to-workspace 8'
  # alt-shift-9 = 'move-node-to-workspace 9'
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
  alt-tab = 'workspace-back-and-forth'
  # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
  alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
  
  # See: https://nikitabobko.github.io/AeroSpace/commands#mode
  alt-shift-semicolon = 'mode service'
  
  # 'service' binding mode declaration.
  # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
  [mode.service.binding]
  esc = ['reload-config', 'mode main']
  r = ['flatten-workspace-tree', 'mode main'] # reset layout
  ctrl-r = ['enable off', 'enable on']
  #s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
  f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
  backspace = ['close-all-windows-but-current', 'mode main']
  
  alt-shift-h = ['join-with left', 'mode main']
  alt-shift-j = ['join-with down', 'mode main']
  alt-shift-k = ['join-with up', 'mode main']
  alt-shift-l = ['join-with right', 'mode main']
  
  # assign workspaces
  [workspace-to-monitor-force-assignment]
  1 = 1
  2 = 2
  3 = 3
  
  # float windows
  [[on-window-detected]]
  if.app-id = 'com.googlecode.iterm2'
  if.window-title-regex-substring = 'iTerm2 Hotkey Window'
  run = ['layout floating']
  
  [[on-window-detected]]
  if.app-id = 'com.google.android.studio'
  if.window-title-regex-substring = 'Running Devices.+'
  run = ['layout floating']
  
  [[on-window-detected]]
  if.app-id = 'cc.ffitch.shottr'
  run = 'layout floating'
  
  [[on-window-detected]]
  if.app-id = 'com.apple.iphonesimulator'
  run = 'layout floating'
  
  [[on-window-detected]]
  if.app-id = 'com.colliderli.iina'
  run = 'layout floating'
  
  [[on-window-detected]]
  if.app-id = 'net.freemacsoft.AppCleaner'
  run = 'layout floating'
  
  [[on-window-detected]]
  if.app-id = 'com.windscribe.gui.macos'
  run = 'layout floating'
  ```
</details>

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - incorrect layout
  - container layout
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - layout
  - container

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by rtuszik** [comment]
The same issue arises for me with default set to tiling. 
<details><summary>config</summary>
<p>

```toml
after-login-command = []
after-startup-command = ['exec-and-forget sketchybar']

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 6
inner.vertical =   6
outer.left =       6
outer.right =      6
outer.bottom =     10
outer.top =        10

# Workspace to Monitor Assignment
[workspace-to-monitor-force-assignment]
1 = 'main'                   # Main Monitor: HP Z32
2 = 'built-in'               # Built-in Display: MacBook
3 = '^Odyssey G40B$'         # Odyssey G40B: Name match

[mode.main.binding]

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-tab = 'workspace-back-and-forth'

alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
check-further-callbacks = true
run = 'layout tiling'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.apple.TextEdit'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.apple.findmy'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.apple.Home'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
run = ['layout floating'] 


[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.apple.PhotoBooth'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'org.mozilla.com.zen.browser'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['layout floating', 'move-node-to-workspace 3'] 
```
</p>
</details>
