### ISSUE TITLE
Pulsing/flickering windows when switching focus left and right back and forth

### ISSUE THREAD

**Issue by RobinRuf** [nikitabobko/AeroSpace#589]
Hey guys,

I encounter a strange behavior when changing focus in a specific order.
In the Video below, I started with changing focus from right to left. So with ALT-h only, I switched from Wezterm to Arc and so on.
After a while, I changed the direction and changing focus from left to right. So with ALT-L only, I switched from Arc to Wezterm and so on.
And then the weird behavior appears. When changing the focus from Arc (on the left) to Wezterm (on the right) with ALT-L, Arc is pulsing. And when I use ALT-L again to change focus from Wezterm to Arc, Wezterm is changing position for a short time.

I am using the latest Verion of OSX: Sequoia 15.0.1

I already reinstalled Aerospace again, but encounter the same behavior.

https://github.com/user-attachments/assets/3618f0ab-61d4-4e82-94cb-43d47f142c3c

## Checklist
- [ x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - focus
  - switch window focus
  - direction
 
- [ x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
```
aerospace CLI client version: 0.14.2-Beta
```

**Comment by nikitabobko** [comment]
Interesting! If you didn't attach the video, I'd not believe you :)

Does it happen only with Arc/WezTerm pair?

**Comment by RobinRuf** [comment]
Haha that's why I attached the video 😅

No, it happens with every combination of applications. (and also with more than 2 windows, and always these on the left side has this behavior)

"Displays have separate Spaces" is on default, so "true" I think - I though this setting is only implrtant if you have multiple screens - but I can test it later when I'm home.

**Comment by RobinRuf** [comment]
UPDATE:
Still same issue after I disabled "Displays have separate Spaces"

**Comment by RobinRuf** [comment]
Well, it looks like reinstalling it for the third time fixed the issue somehow...
Solved, I think..

**Comment by corpooo** [comment]
https://github.com/user-attachments/assets/46a7398f-087c-4b35-a73b-a79fb163b33f

<img width="1768" height="2456" alt="Image" src="https://github.com/user-attachments/assets/b8005dc0-64c4-4203-b7de-fb3dcc3aa7a3" />

It seems like this issues is still present.
I tried with both `Screens have separate Displays` on and off.
I am using my macbook in clamshell mode, so I only have one external display.

Here's my Aerospace config:
```toml
config-version = 2
after-login-command = []

# after-startup-command = [
#   'exec-and-forget ~/.config/aerospace/scripts/aerospace-mode.sh'
# ]

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]
ctrl-shift-alt-left = 'focus left'
ctrl-shift-alt-down = 'focus down'
ctrl-shift-alt-up = 'focus up'
ctrl-shift-alt-right = 'focus right'

cmd-alt-left = 'move left'
cmd-alt-down = 'move down'
cmd-alt-up = 'move up'
cmd-alt-right = 'move right'

alt-pageUp = 'focus dfs-next --boundaries-action wrap-around-the-workspace'
alt-pageDown = 'focus dfs-prev --boundaries-action wrap-around-the-workspace'

ctrl-shift-alt-f = 'fullscreen'
ctrl-shift-alt-t = 'layout floating tiling'
ctrl-shift-alt-q = 'reload-config'

cmd-ctrl-shift-alt-left = 'resize width -50'
cmd-ctrl-shift-alt-down = 'resize height -50'
cmd-ctrl-shift-alt-up = 'resize height +50'
cmd-ctrl-shift-alt-right = 'resize width +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-cmd-1 = 'move-node-to-workspace --focus-follows-window 1'
alt-cmd-2 = 'move-node-to-workspace --focus-follows-window 2'
alt-cmd-3 = 'move-node-to-workspace --focus-follows-window 3'
alt-cmd-4 = 'move-node-to-workspace --focus-follows-window 4'
alt-cmd-5 = 'move-node-to-workspace --focus-follows-window 5'
alt-cmd-6 = 'move-node-to-workspace --focus-follows-window 6'
alt-cmd-7 = 'move-node-to-workspace --focus-follows-window 7'
alt-cmd-8 = 'move-node-to-workspace --focus-follows-window 8'
alt-cmd-9 = 'move-node-to-workspace --focus-follows-window 9'
alt-cmd-0 = 'move-node-to-workspace --focus-follows-window 10'

ctrl-shift-alt-esc = 'reload-config'
ctrl-shift-alt-backtick = 'exec-and-forget ~/.config/aerospace/scripts/back-and-forth.sh'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
check-further-callbacks = true
run = 'layout floating'

# Zen
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
check-further-callbacks = true
run = ['move-node-to-workspace 2'] # The callback itself

# Ghostty
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
check-further-callbacks = true
run = ['move-node-to-workspace 1']  # The callback itself

# Cursor
[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
check-further-callbacks = true
run = ['move-node-to-workspace 1']          # The callback itself

# Chrome
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
check-further-callbacks = true
run = ['move-node-to-workspace 3'] # The callback itself

# Helium
[[on-window-detected]]
if.app-id = 'net.imput.helium'
check-further-callbacks = true
run = ['move-node-to-workspace 3'] # The callback itself

# Slack
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
check-further-callbacks = true
run = ['move-node-to-workspace 4']            # The callback itself

# Mail
[[on-window-detected]]
if.app-id = 'com.apple.mail'
check-further-callbacks = true
run = ['move-node-to-workspace 5']

# Proton Mail
[[on-window-detected]]
if.app-id = 'ch.protonmail.desktop'
check-further-callbacks = true
run = ['move-node-to-workspace 5']

# BusyCal
[[on-window-detected]]
if.app-id = 'com.busymac.busycal-setapp'
check-further-callbacks = true
run = ['move-node-to-workspace 5']

# Calendar
[[on-window-detected]]
if.app-id = 'com.apple.calendar'
check-further-callbacks = true
run = ['move-node-to-workspace 5']

# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
[exec] # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true # If you don't touch "exec" section,
[exec.env-vars] # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'
```

Here's my Aerospace version:
```sh
andokorr@192 ~> aerospace --version
aerospace CLI client version: 0.20.0-Beta 1ec4234a25091225ca2442c2d37e45432dd1b347
AeroSpace.app server version: 0.20.0-Beta 1ec4234a25091225ca2442c2d37e45432dd1b347
```

Here's my Macbook info:
<img width="834" height="1284" alt="Image" src="https://github.com/user-attachments/assets/fca710d0-d621-4215-814e-b501c5115829" />

Let me know if there's any extra info you would like or need.
