### ISSUE TITLE
exec-and-forget open appliations not working

### ISSUE THREAD

**Issue by chivalryq** [nikitabobko/AeroSpace#69]
Hi! Aerospace is great so far. I'm trying to replace my yabai with aerospace and here's my question:

1. As title says, exec-and-forget to open an app not working.
2. How can I check logs if something's wrong?
3. What's the right way to escape a quotation marks and do I need to?

**Update**
4. A question, after fullscreen a window, If I switch with focus, then it will be "de-fullscreened". Is this a designed behavior?

Here's my config

```toml
# This works
alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# Not working
cmd-ctrl-h = 'exec-and-forget open -a Lark'
cmd-ctrl-j = 'exec-and-forget open -a iTerm'
cmd-ctrl-k = 'exec-and-forget open -a \"Microsoft Edge\"'
cmd-ctrl-l = 'exec-and-forget open -a Goland'
```

Here's my debug steps:

1. `alt-enter` works so the grammar is ok.
2. I execute `bash -c "open -a Lark"` directly on shell. It works. So the command is ok.
3. I also tried: replace `Lark` with full path.

Thanks in advance for any help!
