### ISSUE TITLE
`workspace prev` cannot work when jump between `--empty no`

### ISSUE THREAD

**Issue by ysl2** [nikitabobko/AeroSpace#718]
I have these bindings:

```toml
[mode.main.binding]
alt-n = "exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace next"
alt-p = "exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace prev"
```

steps to reproduce:

1. open two windows, one on workspae 1, and the other on workspace 9.
2. focus workspace 5
3. press `alt-p`, expect: focus workspace 1. in fact, nothing happen.
4. press `alt-n`, focus workspace 9 as expected.
