### ISSUE TITLE
Workspace 1 defaults to accordion on startup when default is tiles

### ISSUE THREAD

**Issue by barrettluke** [nikitabobko/AeroSpace#905]
Description

I am encountering an issue where Workspace 1 does not follow the default-root-container-layout = 'tiles' configuration in the aerospace.toml file. While all other workspaces are correctly using the 'tiles' layout, Workspace 1 defaults to the 'accordion' layout.

Interestingly, I can manually switch Workspace 1 to the 'tiles' layout by using the shortcut (ctrl-alt-shift-slash = 'layout tiles horizontal vertical'), but this is not the expected behavior.

Steps to Reproduce
	1.	Set the default-root-container-layout = 'tiles' in the aerospace.toml configuration file.
	2.	Launch or switch to Workspace 1.
	3.	Observe that Workspace 1 is still using the 'accordion' layout, even though the default is 'tiles'.
	4.	Manually use ctrl-alt-shift-slash = 'layout tiles horizontal vertical' to switch Workspace 1 to the 'tiles' layout.

Expected Behavior
	•	Workspace 1 should automatically adopt the 'tiles' layout on startup or when switching, without needing to manually invoke the layout switch.

Actual Behavior
	•	Workspace 1 defaults to the 'accordion' layout, even though the default configuration is set to 'tiles'.
	•	Using the shortcut (ctrl-alt-shift-slash = 'layout tiles horizontal vertical') manually switches Workspace 1 to the correct 'tiles' layout.

Environment Details
	•	AeroSpace CLI client version: 0.16.2-Beta 21336ad382539b35fdc94b4fbd55408e10b101f8
	•	AeroSpace.app server version: 0.16.2-Beta 21336ad382539b35fdc94b4fbd55408e10b101f8
	•	Operating System: macOS
	•	ProductName: macOS
	•	ProductVersion: 15.2
	•	BuildVersion: 24C101

Logs/Output

``` toml
    # Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        40
outer.right =      0

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-alt-shift-slash = 'layout tiles horizontal vertical'
ctrl-alt-shift-cmd-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-shift-cmd-h = 'focus left'
ctrl-alt-shift-cmd-j = 'focus down'
ctrl-alt-shift-cmd-k = 'focus up'
ctrl-alt-shift-cmd-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-alt-shift-cmd-minus = 'resize smart -50'
ctrl-alt-shift-cmd-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-alt-shift-cmd-1 = 'workspace 1'
ctrl-alt-shift-cmd-2 = 'workspace 2'
ctrl-alt-shift-cmd-3 = 'workspace 3'
ctrl-alt-shift-cmd-4 = 'workspace 4'
ctrl-alt-shift-cmd-5 = 'workspace 5'
ctrl-alt-shift-cmd-6 = 'workspace 6'
ctrl-alt-shift-cmd-7 = 'workspace 7'
ctrl-alt-shift-cmd-8 = 'workspace 8'
ctrl-alt-shift-cmd-9 = 'workspace 9'
ctrl-alt-shift-cmd-0 = 'workspace 10' # Retina display built-in display
ctrl-alt-shift-cmd-t = 'workspace 11' # Top monitor
# ctrl-alt-shift-cmd-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
# ctrl-alt-shift-cmd-b = 'workspace B'
# ctrl-alt-shift-cmd-c = 'workspace C'
# ctrl-alt-shift-cmd-d = 'workspace D'
# ctrl-alt-shift-cmd-e = 'workspace E'
# ctrl-alt-shift-cmd-f = 'workspace F'
# ctrl-alt-shift-cmd-g = 'workspace G'
# ctrl-alt-shift-cmd-i = 'workspace I'
# ctrl-alt-shift-cmd-m = 'workspace M'
# ctrl-alt-shift-cmd-n = 'workspace N'
# ctrl-alt-shift-cmd-o = 'workspace O'
# ctrl-alt-shift-cmd-p = 'workspace P'
# ctrl-alt-shift-cmd-q = 'workspace Q'
# ctrl-alt-shift-cmd-r = 'workspace R'
# ctrl-alt-shift-cmd-s = 'workspace S'
# ctrl-alt-shift-cmd-t = 'workspace T'
# ctrl-alt-shift-cmd-u = 'workspace U'
# ctrl-alt-shift-cmd-v = 'workspace V'
# ctrl-alt-shift-cmd-w = 'workspace W'
# ctrl-alt-shift-cmd-x = 'workspace X'
# ctrl-alt-shift-cmd-y = 'workspace Y'
# ctrl-alt-shift-cmd-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10' # Retina display built-in display
alt-shift-t = 'move-node-to-workspace 11' # Top monitor
# alt-shift-a = 'move-node-to-workspace A'
# alt-shift-b = 'move-node-to-workspace B'
# alt-shift-c = 'move-node-to-workspace C'
# alt-shift-d = 'move-node-to-workspace D'
# alt-shift-e = 'move-node-to-workspace E'
# alt-shift-f = 'move-node-to-workspace F'
# alt-shift-g = 'move-node-to-workspace G'
# alt-shift-i = 'move-node-to-workspace I'
# alt-shift-m = 'move-node-to-workspace M'
# alt-shift-n = 'move-node-to-workspace N'
# alt-shift-o = 'move-node-to-workspace O'
# alt-shift-p = 'move-node-to-workspace P'
# alt-shift-q = 'move-node-to-workspace Q'
# alt-shift-r = 'move-node-to-workspace R'
# alt-shift-s = 'move-node-to-workspace S'
# alt-shift-t = 'move-node-to-workspace T'
# alt-shift-u = 'move-node-to-workspace U'
# alt-shift-v = 'move-node-to-workspace V'
# alt-shift-w = 'move-node-to-workspace W'
# alt-shift-x = 'move-node-to-workspace X'
# alt-shift-y = 'move-node-to-workspace Y'
# alt-shift-z = 'move-node-to-workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
a = ['layout accordion', 'mode main']  # 'a' for accordion
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

```

Additional Context
	•	This issue persists across restarts.
	•	I’ve confirmed that the aerospace.toml configuration file is correct, and the issue only occurs for Workspace 1.
	•	Similar ticket #734
